/// Passport dial prefixes from bilibili country list.
/// Source: https://passport.bilibili.com/web/generic/country/list
/// (ported from PiliPlus). App SMS APIs take [countryId] as `cid`.
class DialPrefix {
  const DialPrefix({
    required this.id,
    required this.cname,
    required this.countryId,
  });

  /// Passport list id (metadata only).
  final int id;

  /// Localized country/region name (zh).
  final String cname;

  /// International dialing code — sent as App API `cid`.
  final int countryId;

  String get displayDial => '+$countryId';

  @override
  bool operator ==(Object other) =>
      other is DialPrefix && other.id == id;

  @override
  int get hashCode => id.hashCode;
}

/// Full dial-prefix catalog; first entry is mainland China.
const kDialPrefixes = <DialPrefix>[
  DialPrefix(id: 1, cname: '中国大陆', countryId: 86),
  DialPrefix(id: 5, cname: '中国香港特别行政区', countryId: 852),
  DialPrefix(id: 2, cname: '中国澳门特别行政区', countryId: 853),
  DialPrefix(id: 3, cname: '中国台湾', countryId: 886),
  DialPrefix(id: 4, cname: '美国', countryId: 1),
  DialPrefix(id: 6, cname: '比利时', countryId: 32),
  DialPrefix(id: 7, cname: '澳大利亚', countryId: 61),
  DialPrefix(id: 8, cname: '法国', countryId: 33),
  DialPrefix(id: 9, cname: '加拿大', countryId: 1),
  DialPrefix(id: 10, cname: '日本', countryId: 81),
  DialPrefix(id: 11, cname: '新加坡', countryId: 65),
  DialPrefix(id: 12, cname: '韩国', countryId: 82),
  DialPrefix(id: 13, cname: '马来西亚', countryId: 60),
  DialPrefix(id: 14, cname: '英国', countryId: 44),
  DialPrefix(id: 15, cname: '意大利', countryId: 39),
  DialPrefix(id: 16, cname: '德国', countryId: 49),
  DialPrefix(id: 18, cname: '俄罗斯', countryId: 7),
  DialPrefix(id: 19, cname: '新西兰', countryId: 64),
  DialPrefix(id: 153, cname: '瓦利斯群岛和富图纳群岛', countryId: 1681),
  DialPrefix(id: 152, cname: '葡萄牙', countryId: 351),
  DialPrefix(id: 151, cname: '帕劳', countryId: 680),
  DialPrefix(id: 150, cname: '诺福克岛', countryId: 672),
  DialPrefix(id: 149, cname: '挪威', countryId: 47),
  DialPrefix(id: 148, cname: '纽埃岛', countryId: 683),
  DialPrefix(id: 147, cname: '尼日利亚', countryId: 234),
  DialPrefix(id: 146, cname: '尼日尔', countryId: 227),
  DialPrefix(id: 145, cname: '尼加拉瓜', countryId: 505),
  DialPrefix(id: 144, cname: '尼泊尔', countryId: 977),
  DialPrefix(id: 143, cname: '瑙鲁', countryId: 674),
  DialPrefix(id: 154, cname: '格鲁吉亚', countryId: 995),
  DialPrefix(id: 155, cname: '瑞典', countryId: 46),
  DialPrefix(id: 165, cname: '沙特阿拉伯', countryId: 966),
  DialPrefix(id: 164, cname: '桑给巴尔岛', countryId: 259),
  DialPrefix(id: 163, cname: '塞舌尔共和国', countryId: 248),
  DialPrefix(id: 162, cname: '塞浦路斯', countryId: 357),
  DialPrefix(id: 161, cname: '塞内加尔', countryId: 221),
  DialPrefix(id: 160, cname: '塞拉利昂', countryId: 232),
  DialPrefix(id: 159, cname: '萨摩亚，东部', countryId: 684),
  DialPrefix(id: 158, cname: '萨摩亚，西部', countryId: 685),
  DialPrefix(id: 157, cname: '萨尔瓦多', countryId: 503),
  DialPrefix(id: 156, cname: '瑞士', countryId: 41),
  DialPrefix(id: 166, cname: '圣多美和普林西比', countryId: 239),
  DialPrefix(id: 142, cname: '塞尔维亚', countryId: 381),
  DialPrefix(id: 141, cname: '南非', countryId: 27),
  DialPrefix(id: 128, cname: '毛里塔尼亚', countryId: 222),
  DialPrefix(id: 127, cname: '毛里求斯', countryId: 230),
  DialPrefix(id: 126, cname: '马歇尔岛', countryId: 692),
  DialPrefix(id: 125, cname: '马提尼克岛', countryId: 596),
  DialPrefix(id: 124, cname: '马其顿', countryId: 389),
  DialPrefix(id: 123, cname: '马里亚纳岛', countryId: 1670),
  DialPrefix(id: 122, cname: '马里', countryId: 223),
  DialPrefix(id: 121, cname: '马拉维', countryId: 265),
  DialPrefix(id: 120, cname: '马耳他', countryId: 356),
  DialPrefix(id: 119, cname: '马尔代夫', countryId: 960),
  DialPrefix(id: 129, cname: '蒙古', countryId: 976),
  DialPrefix(id: 130, cname: '蒙特塞拉特岛', countryId: 1664),
  DialPrefix(id: 140, cname: '纳米比亚', countryId: 264),
  DialPrefix(id: 139, cname: '墨西哥', countryId: 52),
  DialPrefix(id: 138, cname: '莫桑比克', countryId: 258),
  DialPrefix(id: 137, cname: '摩纳哥', countryId: 377),
  DialPrefix(id: 136, cname: '摩洛哥', countryId: 212),
  DialPrefix(id: 135, cname: '摩尔多瓦', countryId: 373),
  DialPrefix(id: 134, cname: '缅甸', countryId: 95),
  DialPrefix(id: 133, cname: '密克罗尼西亚', countryId: 691),
  DialPrefix(id: 132, cname: '秘鲁', countryId: 51),
  DialPrefix(id: 131, cname: '孟加拉国', countryId: 880),
  DialPrefix(id: 118, cname: '马达加斯加', countryId: 261),
  DialPrefix(id: 167, cname: '圣卢西亚', countryId: 1784),
  DialPrefix(id: 216, cname: '智利', countryId: 56),
  DialPrefix(id: 203, cname: '牙买加', countryId: 1876),
  DialPrefix(id: 202, cname: '叙利亚', countryId: 963),
  DialPrefix(id: 201, cname: '匈牙利', countryId: 36),
  DialPrefix(id: 200, cname: '科特迪瓦', countryId: 225),
  DialPrefix(id: 199, cname: '希腊', countryId: 30),
  DialPrefix(id: 198, cname: '西班牙', countryId: 34),
  DialPrefix(id: 197, cname: '乌兹别克斯坦', countryId: 998),
  DialPrefix(id: 196, cname: '乌拉圭', countryId: 598),
  DialPrefix(id: 195, cname: '乌克兰', countryId: 380),
  DialPrefix(id: 194, cname: '乌干达', countryId: 256),
  DialPrefix(id: 204, cname: '亚美尼亚', countryId: 374),
  DialPrefix(id: 205, cname: '也门', countryId: 967),
  DialPrefix(id: 215, cname: '直布罗陀', countryId: 350),
  DialPrefix(id: 214, cname: '乍得', countryId: 235),
  DialPrefix(id: 213, cname: '赞比亚', countryId: 260),
  DialPrefix(id: 212, cname: '越南', countryId: 84),
  DialPrefix(id: 211, cname: '约旦', countryId: 962),
  DialPrefix(id: 210, cname: '印尼', countryId: 62),
  DialPrefix(id: 209, cname: '印度', countryId: 91),
  DialPrefix(id: 208, cname: '以色列', countryId: 972),
  DialPrefix(id: 207, cname: '伊朗', countryId: 98),
  DialPrefix(id: 206, cname: '伊拉克', countryId: 964),
  DialPrefix(id: 193, cname: '文莱', countryId: 673),
  DialPrefix(id: 192, cname: '委内瑞拉', countryId: 58),
  DialPrefix(id: 191, cname: '维珍群岛(英属)', countryId: 1284),
  DialPrefix(id: 178, cname: '泰国', countryId: 66),
  DialPrefix(id: 177, cname: '索马里', countryId: 252),
  DialPrefix(id: 176, cname: '所罗门群岛', countryId: 677),
  DialPrefix(id: 175, cname: '苏里南', countryId: 597),
  DialPrefix(id: 174, cname: '苏丹', countryId: 249),
  DialPrefix(id: 173, cname: '斯威士兰', countryId: 268),
  DialPrefix(id: 172, cname: '斯洛文尼亚', countryId: 386),
  DialPrefix(id: 171, cname: '斯洛伐克', countryId: 421),
  DialPrefix(id: 170, cname: '斯里兰卡', countryId: 94),
  DialPrefix(id: 169, cname: '圣皮埃尔和密克隆群岛', countryId: 508),
  DialPrefix(id: 179, cname: '坦桑尼亚', countryId: 255),
  DialPrefix(id: 180, cname: '汤加', countryId: 676),
  DialPrefix(id: 190, cname: '维珍群岛(美属)', countryId: 1340),
  DialPrefix(id: 189, cname: '瓦努阿图', countryId: 678),
  DialPrefix(id: 188, cname: '托克劳岛', countryId: 690),
  DialPrefix(id: 187, cname: '土库曼斯坦', countryId: 993),
  DialPrefix(id: 186, cname: '土耳其', countryId: 90),
  DialPrefix(id: 185, cname: '图瓦卢', countryId: 688),
  DialPrefix(id: 184, cname: '突尼斯', countryId: 216),
  DialPrefix(id: 183, cname: '阿森松岛', countryId: 247),
  DialPrefix(id: 182, cname: '特立尼达和多巴哥', countryId: 1868),
  DialPrefix(id: 181, cname: '特克斯和凯科斯', countryId: 1649),
  DialPrefix(id: 168, cname: '圣马力诺', countryId: 378),
  DialPrefix(id: 67, cname: '法属圭亚那', countryId: 594),
  DialPrefix(id: 54, cname: '不丹', countryId: 975),
  DialPrefix(id: 53, cname: '博茨瓦纳', countryId: 267),
  DialPrefix(id: 52, cname: '伯利兹', countryId: 501),
  DialPrefix(id: 51, cname: '玻利维亚', countryId: 591),
  DialPrefix(id: 50, cname: '波兰', countryId: 48),
  DialPrefix(id: 49, cname: '波黑', countryId: 387),
  DialPrefix(id: 48, cname: '波多黎各', countryId: 1787),
  DialPrefix(id: 47, cname: '冰岛', countryId: 354),
  DialPrefix(id: 46, cname: '贝宁', countryId: 229),
  DialPrefix(id: 45, cname: '保加利亚', countryId: 359),
  DialPrefix(id: 55, cname: '布基纳法索', countryId: 226),
  DialPrefix(id: 56, cname: '布隆迪', countryId: 257),
  DialPrefix(id: 66, cname: '法属波利尼西亚', countryId: 689),
  DialPrefix(id: 65, cname: '法罗岛', countryId: 298),
  DialPrefix(id: 64, cname: '厄立特里亚', countryId: 291),
  DialPrefix(id: 63, cname: '厄瓜多尔', countryId: 593),
  DialPrefix(id: 62, cname: '多米尼加代表', countryId: 1809),
  DialPrefix(id: 61, cname: '多米尼加', countryId: 1767),
  DialPrefix(id: 60, cname: '多哥', countryId: 228),
  DialPrefix(id: 59, cname: '迪戈加西亚岛', countryId: 246),
  DialPrefix(id: 58, cname: '丹麦', countryId: 45),
  DialPrefix(id: 57, cname: '赤道几内亚', countryId: 240),
  DialPrefix(id: 44, cname: '百慕大群岛', countryId: 1441),
  DialPrefix(id: 43, cname: '白俄罗斯', countryId: 375),
  DialPrefix(id: 42, cname: '巴西', countryId: 55),
  DialPrefix(id: 29, cname: '爱尔兰', countryId: 353),
  DialPrefix(id: 28, cname: '埃塞俄比亚', countryId: 251),
  DialPrefix(id: 27, cname: '埃及', countryId: 20),
  DialPrefix(id: 26, cname: '阿塞拜疆', countryId: 994),
  DialPrefix(id: 25, cname: '阿曼', countryId: 968),
  DialPrefix(id: 24, cname: '阿联酋', countryId: 971),
  DialPrefix(id: 23, cname: '阿根廷', countryId: 54),
  DialPrefix(id: 22, cname: '阿富汗', countryId: 93),
  DialPrefix(id: 21, cname: '阿尔及利亚', countryId: 213),
  DialPrefix(id: 20, cname: '阿尔巴尼亚', countryId: 355),
  DialPrefix(id: 30, cname: '爱沙尼亚', countryId: 372),
  DialPrefix(id: 31, cname: '安道尔', countryId: 376),
  DialPrefix(id: 41, cname: '巴拿马', countryId: 507),
  DialPrefix(id: 40, cname: '巴林', countryId: 973),
  DialPrefix(id: 39, cname: '巴拉圭', countryId: 595),
  DialPrefix(id: 38, cname: '巴基斯坦', countryId: 92),
  DialPrefix(id: 37, cname: '巴哈马群岛', countryId: 1242),
  DialPrefix(id: 36, cname: '巴布亚新几内亚', countryId: 675),
  DialPrefix(id: 35, cname: '巴巴多斯', countryId: 1246),
  DialPrefix(id: 34, cname: '奥地利', countryId: 43),
  DialPrefix(id: 33, cname: '安提瓜岛和巴布达', countryId: 1268),
  DialPrefix(id: 32, cname: '安哥拉', countryId: 244),
  DialPrefix(id: 68, cname: '非洲中部', countryId: 236),
  DialPrefix(id: 117, cname: '罗马尼亚', countryId: 40),
  DialPrefix(id: 104, cname: '科威特', countryId: 965),
  DialPrefix(id: 103, cname: '科摩罗', countryId: 269),
  DialPrefix(id: 102, cname: '开曼群岛', countryId: 1345),
  DialPrefix(id: 101, cname: '卡塔尔', countryId: 974),
  DialPrefix(id: 100, cname: '喀麦隆', countryId: 237),
  DialPrefix(id: 99, cname: '聚会岛', countryId: 262),
  DialPrefix(id: 98, cname: '津巴布韦', countryId: 263),
  DialPrefix(id: 97, cname: '捷克', countryId: 420),
  DialPrefix(id: 96, cname: '柬埔寨', countryId: 855),
  DialPrefix(id: 95, cname: '加蓬', countryId: 241),
  DialPrefix(id: 105, cname: '克罗地亚', countryId: 385),
  DialPrefix(id: 106, cname: '肯尼亚', countryId: 254),
  DialPrefix(id: 116, cname: '卢旺达', countryId: 250),
  DialPrefix(id: 115, cname: '卢森堡', countryId: 352),
  DialPrefix(id: 114, cname: '利比亚', countryId: 218),
  DialPrefix(id: 113, cname: '利比里亚', countryId: 231),
  DialPrefix(id: 112, cname: '立陶宛', countryId: 370),
  DialPrefix(id: 111, cname: '黎巴嫩', countryId: 961),
  DialPrefix(id: 110, cname: '老挝', countryId: 856),
  DialPrefix(id: 109, cname: '莱索托', countryId: 266),
  DialPrefix(id: 108, cname: '拉脱维亚', countryId: 371),
  DialPrefix(id: 107, cname: '库克岛', countryId: 682),
  DialPrefix(id: 94, cname: '加纳', countryId: 233),
  DialPrefix(id: 93, cname: '几内亚比绍', countryId: 245),
  DialPrefix(id: 92, cname: '几内亚', countryId: 224),
  DialPrefix(id: 79, cname: '格林纳达', countryId: 1473),
  DialPrefix(id: 78, cname: '哥斯达黎加', countryId: 506),
  DialPrefix(id: 77, cname: '哥伦比亚', countryId: 57),
  DialPrefix(id: 76, cname: '刚果(金)', countryId: 243),
  DialPrefix(id: 75, cname: '刚果', countryId: 242),
  DialPrefix(id: 74, cname: '冈比亚', countryId: 220),
  DialPrefix(id: 73, cname: '福克兰岛', countryId: 500),
  DialPrefix(id: 72, cname: '佛得角', countryId: 238),
  DialPrefix(id: 71, cname: '芬兰', countryId: 358),
  DialPrefix(id: 70, cname: '斐济', countryId: 679),
  DialPrefix(id: 80, cname: '格陵兰岛', countryId: 299),
  DialPrefix(id: 81, cname: '古巴', countryId: 53),
  DialPrefix(id: 91, cname: '吉尔吉斯斯坦', countryId: 996),
  DialPrefix(id: 90, cname: '吉布提', countryId: 253),
  DialPrefix(id: 89, cname: '基里巴斯', countryId: 686),
  DialPrefix(id: 88, cname: '维克岛', countryId: 1808),
  DialPrefix(id: 87, cname: '洪都拉斯', countryId: 504),
  DialPrefix(id: 86, cname: '荷兰', countryId: 31),
  DialPrefix(id: 85, cname: '朝鲜', countryId: 850),
  DialPrefix(id: 84, cname: '海地', countryId: 509),
  DialPrefix(id: 83, cname: '关岛', countryId: 1671),
  DialPrefix(id: 82, cname: '瓜德罗普岛', countryId: 590),
  DialPrefix(id: 69, cname: '菲律宾', countryId: 63),
];

DialPrefix dialPrefixByCountryId(int countryId) {
  for (final e in kDialPrefixes) {
    if (e.countryId == countryId) return e;
  }
  return kDialPrefixes.first;
}

DialPrefix dialPrefixById(int id) {
  for (final e in kDialPrefixes) {
    if (e.id == id) return e;
  }
  return kDialPrefixes.first;
}
