// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AccountPublicDto {
  final String id;
  final PlatformInt64 mid;
  final String name;
  final String avatarUrl;
  final bool isLogin;

  const AccountPublicDto({
    required this.id,
    required this.mid,
    required this.name,
    required this.avatarUrl,
    required this.isLogin,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mid.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      isLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountPublicDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mid == other.mid &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          isLogin == other.isLogin;
}

class CaptchaDto {
  final String token;
  final String gt;
  final String challenge;
  final String captchaType;

  const CaptchaDto({
    required this.token,
    required this.gt,
    required this.challenge,
    required this.captchaType,
  });

  @override
  int get hashCode =>
      token.hashCode ^ gt.hashCode ^ challenge.hashCode ^ captchaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptchaDto &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          gt == other.gt &&
          challenge == other.challenge &&
          captchaType == other.captchaType;
}

class QrPollDto {
  final QrStatusKind status;
  final String message;
  final AccountPublicDto? account;

  const QrPollDto({required this.status, required this.message, this.account});

  @override
  int get hashCode => status.hashCode ^ message.hashCode ^ account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrPollDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          message == other.message &&
          account == other.account;
}

class QrStartDto {
  final String url;
  final String authCode;

  const QrStartDto({required this.url, required this.authCode});

  @override
  int get hashCode => url.hashCode ^ authCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrStartDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          authCode == other.authCode;
}

enum QrStatusKind { pending, scanned, confirmed, expired, error }

enum SlotDto { main, heartbeat, recommend, video }

class SmsLoginDto {
  final int cid;
  final String tel;
  final String code;
  final String captchaKey;
  final String loginSessionId;

  const SmsLoginDto({
    required this.cid,
    required this.tel,
    required this.code,
    required this.captchaKey,
    required this.loginSessionId,
  });

  @override
  int get hashCode =>
      cid.hashCode ^
      tel.hashCode ^
      code.hashCode ^
      captchaKey.hashCode ^
      loginSessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmsLoginDto &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          tel == other.tel &&
          code == other.code &&
          captchaKey == other.captchaKey &&
          loginSessionId == other.loginSessionId;
}

class SmsSendDto {
  /// Passport country id (中国大陆 = 1).
  final int cid;
  final String tel;
  final String token;
  final String geeChallenge;
  final String geeValidate;
  final String geeSeccode;
  final String loginSessionId;
  final String? localId;

  const SmsSendDto({
    required this.cid,
    required this.tel,
    required this.token,
    required this.geeChallenge,
    required this.geeValidate,
    required this.geeSeccode,
    required this.loginSessionId,
    this.localId,
  });

  @override
  int get hashCode =>
      cid.hashCode ^
      tel.hashCode ^
      token.hashCode ^
      geeChallenge.hashCode ^
      geeValidate.hashCode ^
      geeSeccode.hashCode ^
      loginSessionId.hashCode ^
      localId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmsSendDto &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          tel == other.tel &&
          token == other.token &&
          geeChallenge == other.geeChallenge &&
          geeValidate == other.geeValidate &&
          geeSeccode == other.geeSeccode &&
          loginSessionId == other.loginSessionId &&
          localId == other.localId;
}

class SmsSendDtoResult {
  final String captchaKey;
  final String loginSessionId;

  const SmsSendDtoResult({
    required this.captchaKey,
    required this.loginSessionId,
  });

  @override
  int get hashCode => captchaKey.hashCode ^ loginSessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmsSendDtoResult &&
          runtimeType == other.runtimeType &&
          captchaKey == other.captchaKey &&
          loginSessionId == other.loginSessionId;
}
