// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Error returned across the FFI boundary.
class AppError implements FrbException {
  final ErrorKind kind;
  final String message;
  final int? biliCode;

  const AppError({required this.kind, required this.message, this.biliCode});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ biliCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          biliCode == other.biliCode;
}

/// FFI-facing error kind.
enum ErrorKind {
  unauthenticated,
  csrf,
  riskControl,
  notFound,
  rateLimited,
  invalidArgument,
  network,
  parse,
  storage,
  internal,
}
