// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/dynamics.dart';
import 'api/engagement.dart';
import 'api/feed.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'api/social.dart';
import 'api/user.dart';
import 'api/video.dart';
import 'auth_service.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountPublicDto dco_decode_account_public_dto(dynamic raw);

  @protected
  ApiVersion dco_decode_api_version(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  ArchiveRelationDto dco_decode_archive_relation_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapConfig dco_decode_bootstrap_config(dynamic raw);

  @protected
  AccountPublicDto dco_decode_box_autoadd_account_public_dto(dynamic raw);

  @protected
  BootstrapConfig dco_decode_box_autoadd_bootstrap_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PasswordLoginDto dco_decode_box_autoadd_password_login_dto(dynamic raw);

  @protected
  PasswordRiskDto dco_decode_box_autoadd_password_risk_dto(dynamic raw);

  @protected
  PasswordRiskSendSmsDto dco_decode_box_autoadd_password_risk_send_sms_dto(
    dynamic raw,
  );

  @protected
  PasswordRiskVerifyDto dco_decode_box_autoadd_password_risk_verify_dto(
    dynamic raw,
  );

  @protected
  SmsLoginDto dco_decode_box_autoadd_sms_login_dto(dynamic raw);

  @protected
  SmsSendDto dco_decode_box_autoadd_sms_send_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CaptchaDto dco_decode_captcha_dto(dynamic raw);

  @protected
  DanmakuItemDto dco_decode_danmaku_item_dto(dynamic raw);

  @protected
  DanmakuSegmentDto dco_decode_danmaku_segment_dto(dynamic raw);

  @protected
  DynamicItemDto dco_decode_dynamic_item_dto(dynamic raw);

  @protected
  DynamicPageDto dco_decode_dynamic_page_dto(dynamic raw);

  @protected
  ErrorKind dco_decode_error_kind(dynamic raw);

  @protected
  FavFolderDto dco_decode_fav_folder_dto(dynamic raw);

  @protected
  FavFolderListDto dco_decode_fav_folder_list_dto(dynamic raw);

  @protected
  FavResourceItemDto dco_decode_fav_resource_item_dto(dynamic raw);

  @protected
  FavResourcePageDto dco_decode_fav_resource_page_dto(dynamic raw);

  @protected
  FeedItemDto dco_decode_feed_item_dto(dynamic raw);

  @protected
  HeaderDto dco_decode_header_dto(dynamic raw);

  @protected
  HistoryItemDto dco_decode_history_item_dto(dynamic raw);

  @protected
  HistoryPageDto dco_decode_history_page_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountPublicDto> dco_decode_list_account_public_dto(dynamic raw);

  @protected
  List<DanmakuItemDto> dco_decode_list_danmaku_item_dto(dynamic raw);

  @protected
  List<DynamicItemDto> dco_decode_list_dynamic_item_dto(dynamic raw);

  @protected
  List<FavFolderDto> dco_decode_list_fav_folder_dto(dynamic raw);

  @protected
  List<FavResourceItemDto> dco_decode_list_fav_resource_item_dto(dynamic raw);

  @protected
  List<FeedItemDto> dco_decode_list_feed_item_dto(dynamic raw);

  @protected
  List<HeaderDto> dco_decode_list_header_dto(dynamic raw);

  @protected
  List<HistoryItemDto> dco_decode_list_history_item_dto(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReplyDto> dco_decode_list_reply_dto(dynamic raw);

  @protected
  List<SearchVideoItemDto> dco_decode_list_search_video_item_dto(dynamic raw);

  @protected
  List<StreamDto> dco_decode_list_stream_dto(dynamic raw);

  @protected
  List<SubtitleTrackDto> dco_decode_list_subtitle_track_dto(dynamic raw);

  @protected
  List<ToViewItemDto> dco_decode_list_to_view_item_dto(dynamic raw);

  @protected
  List<VideoPageDto> dco_decode_list_video_page_dto(dynamic raw);

  @protected
  MediaFormatDto dco_decode_media_format_dto(dynamic raw);

  @protected
  MediaSourceDto dco_decode_media_source_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccountPublicDto? dco_decode_opt_box_autoadd_account_public_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PasswordRiskDto? dco_decode_opt_box_autoadd_password_risk_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PasswordLoginDto dco_decode_password_login_dto(dynamic raw);

  @protected
  PasswordLoginResultDto dco_decode_password_login_result_dto(dynamic raw);

  @protected
  PasswordLoginResultKind dco_decode_password_login_result_kind(dynamic raw);

  @protected
  PasswordRiskDto dco_decode_password_risk_dto(dynamic raw);

  @protected
  PasswordRiskSendSmsDto dco_decode_password_risk_send_sms_dto(dynamic raw);

  @protected
  PasswordRiskSendSmsResultDto dco_decode_password_risk_send_sms_result_dto(
    dynamic raw,
  );

  @protected
  PasswordRiskVerifyDto dco_decode_password_risk_verify_dto(dynamic raw);

  @protected
  PopularFeedDto dco_decode_popular_feed_dto(dynamic raw);

  @protected
  QrPollDto dco_decode_qr_poll_dto(dynamic raw);

  @protected
  QrStartDto dco_decode_qr_start_dto(dynamic raw);

  @protected
  QrStatusKind dco_decode_qr_status_kind(dynamic raw);

  @protected
  RecommendFeedDto dco_decode_recommend_feed_dto(dynamic raw);

  @protected
  ReplyDto dco_decode_reply_dto(dynamic raw);

  @protected
  ReplyListDto dco_decode_reply_list_dto(dynamic raw);

  @protected
  SearchSuggestDto dco_decode_search_suggest_dto(dynamic raw);

  @protected
  SearchVideoItemDto dco_decode_search_video_item_dto(dynamic raw);

  @protected
  SearchVideoPageDto dco_decode_search_video_page_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw);

  @protected
  SlotDto dco_decode_slot_dto(dynamic raw);

  @protected
  SmsLoginDto dco_decode_sms_login_dto(dynamic raw);

  @protected
  SmsSendDto dco_decode_sms_send_dto(dynamic raw);

  @protected
  SmsSendDtoResult dco_decode_sms_send_dto_result(dynamic raw);

  @protected
  StreamDto dco_decode_stream_dto(dynamic raw);

  @protected
  SubtitleTrackDto dco_decode_subtitle_track_dto(dynamic raw);

  @protected
  ToViewItemDto dco_decode_to_view_item_dto(dynamic raw);

  @protected
  ToViewPageDto dco_decode_to_view_page_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoDetailDto dco_decode_video_detail_dto(dynamic raw);

  @protected
  VideoPageDto dco_decode_video_page_dto(dynamic raw);

  @protected
  VideoStatDto dco_decode_video_stat_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountPublicDto sse_decode_account_public_dto(SseDeserializer deserializer);

  @protected
  ApiVersion sse_decode_api_version(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  ArchiveRelationDto sse_decode_archive_relation_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapConfig sse_decode_bootstrap_config(SseDeserializer deserializer);

  @protected
  AccountPublicDto sse_decode_box_autoadd_account_public_dto(
    SseDeserializer deserializer,
  );

  @protected
  BootstrapConfig sse_decode_box_autoadd_bootstrap_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PasswordLoginDto sse_decode_box_autoadd_password_login_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordRiskDto sse_decode_box_autoadd_password_risk_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordRiskSendSmsDto sse_decode_box_autoadd_password_risk_send_sms_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordRiskVerifyDto sse_decode_box_autoadd_password_risk_verify_dto(
    SseDeserializer deserializer,
  );

  @protected
  SmsLoginDto sse_decode_box_autoadd_sms_login_dto(
    SseDeserializer deserializer,
  );

  @protected
  SmsSendDto sse_decode_box_autoadd_sms_send_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CaptchaDto sse_decode_captcha_dto(SseDeserializer deserializer);

  @protected
  DanmakuItemDto sse_decode_danmaku_item_dto(SseDeserializer deserializer);

  @protected
  DanmakuSegmentDto sse_decode_danmaku_segment_dto(
    SseDeserializer deserializer,
  );

  @protected
  DynamicItemDto sse_decode_dynamic_item_dto(SseDeserializer deserializer);

  @protected
  DynamicPageDto sse_decode_dynamic_page_dto(SseDeserializer deserializer);

  @protected
  ErrorKind sse_decode_error_kind(SseDeserializer deserializer);

  @protected
  FavFolderDto sse_decode_fav_folder_dto(SseDeserializer deserializer);

  @protected
  FavFolderListDto sse_decode_fav_folder_list_dto(SseDeserializer deserializer);

  @protected
  FavResourceItemDto sse_decode_fav_resource_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FavResourcePageDto sse_decode_fav_resource_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  FeedItemDto sse_decode_feed_item_dto(SseDeserializer deserializer);

  @protected
  HeaderDto sse_decode_header_dto(SseDeserializer deserializer);

  @protected
  HistoryItemDto sse_decode_history_item_dto(SseDeserializer deserializer);

  @protected
  HistoryPageDto sse_decode_history_page_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountPublicDto> sse_decode_list_account_public_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DanmakuItemDto> sse_decode_list_danmaku_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DynamicItemDto> sse_decode_list_dynamic_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FavFolderDto> sse_decode_list_fav_folder_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FavResourceItemDto> sse_decode_list_fav_resource_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FeedItemDto> sse_decode_list_feed_item_dto(SseDeserializer deserializer);

  @protected
  List<HeaderDto> sse_decode_list_header_dto(SseDeserializer deserializer);

  @protected
  List<HistoryItemDto> sse_decode_list_history_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReplyDto> sse_decode_list_reply_dto(SseDeserializer deserializer);

  @protected
  List<SearchVideoItemDto> sse_decode_list_search_video_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<StreamDto> sse_decode_list_stream_dto(SseDeserializer deserializer);

  @protected
  List<SubtitleTrackDto> sse_decode_list_subtitle_track_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ToViewItemDto> sse_decode_list_to_view_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<VideoPageDto> sse_decode_list_video_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  MediaFormatDto sse_decode_media_format_dto(SseDeserializer deserializer);

  @protected
  MediaSourceDto sse_decode_media_source_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccountPublicDto? sse_decode_opt_box_autoadd_account_public_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PasswordRiskDto? sse_decode_opt_box_autoadd_password_risk_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PasswordLoginDto sse_decode_password_login_dto(SseDeserializer deserializer);

  @protected
  PasswordLoginResultDto sse_decode_password_login_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordLoginResultKind sse_decode_password_login_result_kind(
    SseDeserializer deserializer,
  );

  @protected
  PasswordRiskDto sse_decode_password_risk_dto(SseDeserializer deserializer);

  @protected
  PasswordRiskSendSmsDto sse_decode_password_risk_send_sms_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordRiskSendSmsResultDto sse_decode_password_risk_send_sms_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordRiskVerifyDto sse_decode_password_risk_verify_dto(
    SseDeserializer deserializer,
  );

  @protected
  PopularFeedDto sse_decode_popular_feed_dto(SseDeserializer deserializer);

  @protected
  QrPollDto sse_decode_qr_poll_dto(SseDeserializer deserializer);

  @protected
  QrStartDto sse_decode_qr_start_dto(SseDeserializer deserializer);

  @protected
  QrStatusKind sse_decode_qr_status_kind(SseDeserializer deserializer);

  @protected
  RecommendFeedDto sse_decode_recommend_feed_dto(SseDeserializer deserializer);

  @protected
  ReplyDto sse_decode_reply_dto(SseDeserializer deserializer);

  @protected
  ReplyListDto sse_decode_reply_list_dto(SseDeserializer deserializer);

  @protected
  SearchSuggestDto sse_decode_search_suggest_dto(SseDeserializer deserializer);

  @protected
  SearchVideoItemDto sse_decode_search_video_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchVideoPageDto sse_decode_search_video_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer);

  @protected
  SlotDto sse_decode_slot_dto(SseDeserializer deserializer);

  @protected
  SmsLoginDto sse_decode_sms_login_dto(SseDeserializer deserializer);

  @protected
  SmsSendDto sse_decode_sms_send_dto(SseDeserializer deserializer);

  @protected
  SmsSendDtoResult sse_decode_sms_send_dto_result(SseDeserializer deserializer);

  @protected
  StreamDto sse_decode_stream_dto(SseDeserializer deserializer);

  @protected
  SubtitleTrackDto sse_decode_subtitle_track_dto(SseDeserializer deserializer);

  @protected
  ToViewItemDto sse_decode_to_view_item_dto(SseDeserializer deserializer);

  @protected
  ToViewPageDto sse_decode_to_view_page_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoDetailDto sse_decode_video_detail_dto(SseDeserializer deserializer);

  @protected
  VideoPageDto sse_decode_video_page_dto(SseDeserializer deserializer);

  @protected
  VideoStatDto sse_decode_video_stat_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_public_dto(
    AccountPublicDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_version(ApiVersion self, SseSerializer serializer);

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_archive_relation_dto(
    ArchiveRelationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_config(
    BootstrapConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_account_public_dto(
    AccountPublicDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bootstrap_config(
    BootstrapConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_password_login_dto(
    PasswordLoginDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_password_risk_dto(
    PasswordRiskDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_password_risk_send_sms_dto(
    PasswordRiskSendSmsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_password_risk_verify_dto(
    PasswordRiskVerifyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sms_login_dto(
    SmsLoginDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sms_send_dto(
    SmsSendDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_captcha_dto(CaptchaDto self, SseSerializer serializer);

  @protected
  void sse_encode_danmaku_item_dto(
    DanmakuItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_danmaku_segment_dto(
    DanmakuSegmentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dynamic_item_dto(
    DynamicItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dynamic_page_dto(
    DynamicPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_error_kind(ErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_fav_folder_dto(FavFolderDto self, SseSerializer serializer);

  @protected
  void sse_encode_fav_folder_list_dto(
    FavFolderListDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fav_resource_item_dto(
    FavResourceItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fav_resource_page_dto(
    FavResourcePageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_feed_item_dto(FeedItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_header_dto(HeaderDto self, SseSerializer serializer);

  @protected
  void sse_encode_history_item_dto(
    HistoryItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_page_dto(
    HistoryPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_public_dto(
    List<AccountPublicDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_danmaku_item_dto(
    List<DanmakuItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dynamic_item_dto(
    List<DynamicItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fav_folder_dto(
    List<FavFolderDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fav_resource_item_dto(
    List<FavResourceItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_feed_item_dto(
    List<FeedItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_header_dto(
    List<HeaderDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_item_dto(
    List<HistoryItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reply_dto(List<ReplyDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_search_video_item_dto(
    List<SearchVideoItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stream_dto(
    List<StreamDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subtitle_track_dto(
    List<SubtitleTrackDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_to_view_item_dto(
    List<ToViewItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_video_page_dto(
    List<VideoPageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_format_dto(
    MediaFormatDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_source_dto(
    MediaSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account_public_dto(
    AccountPublicDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_password_risk_dto(
    PasswordRiskDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_password_login_dto(
    PasswordLoginDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_login_result_dto(
    PasswordLoginResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_login_result_kind(
    PasswordLoginResultKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_risk_dto(
    PasswordRiskDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_risk_send_sms_dto(
    PasswordRiskSendSmsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_risk_send_sms_result_dto(
    PasswordRiskSendSmsResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_risk_verify_dto(
    PasswordRiskVerifyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_popular_feed_dto(
    PopularFeedDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qr_poll_dto(QrPollDto self, SseSerializer serializer);

  @protected
  void sse_encode_qr_start_dto(QrStartDto self, SseSerializer serializer);

  @protected
  void sse_encode_qr_status_kind(QrStatusKind self, SseSerializer serializer);

  @protected
  void sse_encode_recommend_feed_dto(
    RecommendFeedDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reply_dto(ReplyDto self, SseSerializer serializer);

  @protected
  void sse_encode_reply_list_dto(ReplyListDto self, SseSerializer serializer);

  @protected
  void sse_encode_search_suggest_dto(
    SearchSuggestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_video_item_dto(
    SearchVideoItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_video_page_dto(
    SearchVideoPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_slot_dto(SlotDto self, SseSerializer serializer);

  @protected
  void sse_encode_sms_login_dto(SmsLoginDto self, SseSerializer serializer);

  @protected
  void sse_encode_sms_send_dto(SmsSendDto self, SseSerializer serializer);

  @protected
  void sse_encode_sms_send_dto_result(
    SmsSendDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stream_dto(StreamDto self, SseSerializer serializer);

  @protected
  void sse_encode_subtitle_track_dto(
    SubtitleTrackDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_to_view_item_dto(
    ToViewItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_to_view_page_dto(
    ToViewPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_detail_dto(
    VideoDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_video_page_dto(VideoPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_video_stat_dto(VideoStatDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
