// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/feed.dart';
import 'api/simple.dart';
import 'api/video.dart';
import 'auth_service.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -2014172865;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'core',
        ioDirectory: '../crates/core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  ApiVersion crateApiSimpleApiVersion();

  Future<void> crateApiSimpleBootstrap({required BootstrapConfig config});

  String crateApiAuthDeviceBuvid3();

  Future<PopularFeedDto> crateApiFeedFeedPopular({
    required int pn,
    required int ps,
  });

  Future<RecommendFeedDto> crateApiFeedFeedRecommend({
    required int freshIdx,
    required int ps,
  });

  Future<void> crateApiSimpleInitApp();

  List<AccountPublicDto> crateApiAuthListAccounts();

  Future<CaptchaDto> crateApiAuthLoginCaptcha();

  Future<QrPollDto> crateApiAuthLoginQrPoll({
    required String authCode,
    String? localId,
  });

  Future<QrStartDto> crateApiAuthLoginQrStart({String? localId});

  Future<AccountPublicDto> crateApiAuthLoginSms({required SmsLoginDto req});

  Future<SmsSendDtoResult> crateApiAuthLoginSmsSend({required SmsSendDto req});

  void crateApiAuthLogout({String? accountId});

  String crateApiAuthNewLoginSessionId();

  String crateApiSimplePing();

  Future<MediaSourceDto> crateApiVideoPlayUrl({
    required String id,
    required PlatformInt64 cid,
    required int qn,
    required int fnval,
  });

  Future<void> crateApiVideoPlaybackStart({
    required PlatformInt64 aid,
    required String bvid,
    required PlatformInt64 cid,
  });

  void crateApiVideoPlaybackStop();

  void crateApiAuthSetAccountSlot({required SlotDto slot, String? accountId});

  Future<VideoDetailDto> crateApiVideoVideoDetail({required String id});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ApiVersion crateApiSimpleApiVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_version,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApiVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiVersionConstMeta =>
      const TaskConstMeta(debugName: "api_version", argNames: []);

  @override
  Future<void> crateApiSimpleBootstrap({required BootstrapConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bootstrap_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiSimpleBootstrapConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleBootstrapConstMeta =>
      const TaskConstMeta(debugName: "bootstrap", argNames: ["config"]);

  @override
  String crateApiAuthDeviceBuvid3() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthDeviceBuvid3ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthDeviceBuvid3ConstMeta =>
      const TaskConstMeta(debugName: "device_buvid3", argNames: []);

  @override
  Future<PopularFeedDto> crateApiFeedFeedPopular({
    required int pn,
    required int ps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(pn, serializer);
          sse_encode_u_32(ps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_popular_feed_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedFeedPopularConstMeta,
        argValues: [pn, ps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedFeedPopularConstMeta =>
      const TaskConstMeta(debugName: "feed_popular", argNames: ["pn", "ps"]);

  @override
  Future<RecommendFeedDto> crateApiFeedFeedRecommend({
    required int freshIdx,
    required int ps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(freshIdx, serializer);
          sse_encode_u_32(ps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recommend_feed_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiFeedFeedRecommendConstMeta,
        argValues: [freshIdx, ps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFeedFeedRecommendConstMeta => const TaskConstMeta(
    debugName: "feed_recommend",
    argNames: ["freshIdx", "ps"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<AccountPublicDto> crateApiAuthListAccounts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_account_public_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthListAccountsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthListAccountsConstMeta =>
      const TaskConstMeta(debugName: "list_accounts", argNames: []);

  @override
  Future<CaptchaDto> crateApiAuthLoginCaptcha() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_captcha_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthLoginCaptchaConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLoginCaptchaConstMeta =>
      const TaskConstMeta(debugName: "login_captcha", argNames: []);

  @override
  Future<QrPollDto> crateApiAuthLoginQrPoll({
    required String authCode,
    String? localId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(authCode, serializer);
          sse_encode_opt_String(localId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_poll_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthLoginQrPollConstMeta,
        argValues: [authCode, localId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLoginQrPollConstMeta => const TaskConstMeta(
    debugName: "login_qr_poll",
    argNames: ["authCode", "localId"],
  );

  @override
  Future<QrStartDto> crateApiAuthLoginQrStart({String? localId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(localId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_start_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthLoginQrStartConstMeta,
        argValues: [localId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLoginQrStartConstMeta =>
      const TaskConstMeta(debugName: "login_qr_start", argNames: ["localId"]);

  @override
  Future<AccountPublicDto> crateApiAuthLoginSms({required SmsLoginDto req}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_sms_login_dto(req, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_public_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthLoginSmsConstMeta,
        argValues: [req],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLoginSmsConstMeta =>
      const TaskConstMeta(debugName: "login_sms", argNames: ["req"]);

  @override
  Future<SmsSendDtoResult> crateApiAuthLoginSmsSend({required SmsSendDto req}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_sms_send_dto(req, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sms_send_dto_result,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthLoginSmsSendConstMeta,
        argValues: [req],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLoginSmsSendConstMeta =>
      const TaskConstMeta(debugName: "login_sms_send", argNames: ["req"]);

  @override
  void crateApiAuthLogout({String? accountId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(accountId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthLogoutConstMeta,
        argValues: [accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: ["accountId"]);

  @override
  String crateApiAuthNewLoginSessionId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthNewLoginSessionIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthNewLoginSessionIdConstMeta =>
      const TaskConstMeta(debugName: "new_login_session_id", argNames: []);

  @override
  String crateApiSimplePing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @override
  Future<MediaSourceDto> crateApiVideoPlayUrl({
    required String id,
    required PlatformInt64 cid,
    required int qn,
    required int fnval,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_i_64(cid, serializer);
          sse_encode_u_32(qn, serializer);
          sse_encode_u_32(fnval, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_source_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVideoPlayUrlConstMeta,
        argValues: [id, cid, qn, fnval],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoPlayUrlConstMeta => const TaskConstMeta(
    debugName: "play_url",
    argNames: ["id", "cid", "qn", "fnval"],
  );

  @override
  Future<void> crateApiVideoPlaybackStart({
    required PlatformInt64 aid,
    required String bvid,
    required PlatformInt64 cid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(aid, serializer);
          sse_encode_String(bvid, serializer);
          sse_encode_i_64(cid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVideoPlaybackStartConstMeta,
        argValues: [aid, bvid, cid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoPlaybackStartConstMeta => const TaskConstMeta(
    debugName: "playback_start",
    argNames: ["aid", "bvid", "cid"],
  );

  @override
  void crateApiVideoPlaybackStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVideoPlaybackStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoPlaybackStopConstMeta =>
      const TaskConstMeta(debugName: "playback_stop", argNames: []);

  @override
  void crateApiAuthSetAccountSlot({required SlotDto slot, String? accountId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_slot_dto(slot, serializer);
          sse_encode_opt_String(accountId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiAuthSetAccountSlotConstMeta,
        argValues: [slot, accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthSetAccountSlotConstMeta => const TaskConstMeta(
    debugName: "set_account_slot",
    argNames: ["slot", "accountId"],
  );

  @override
  Future<VideoDetailDto> crateApiVideoVideoDetail({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_detail_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVideoVideoDetailConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoVideoDetailConstMeta =>
      const TaskConstMeta(debugName: "video_detail", argNames: ["id"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountPublicDto dco_decode_account_public_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AccountPublicDto(
      id: dco_decode_String(arr[0]),
      mid: dco_decode_i_64(arr[1]),
      name: dco_decode_String(arr[2]),
      avatarUrl: dco_decode_String(arr[3]),
      isLogin: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ApiVersion dco_decode_api_version(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApiVersion(
      major: dco_decode_u_32(arr[0]),
      minor: dco_decode_u_32(arr[1]),
      patch: dco_decode_u_32(arr[2]),
      core: dco_decode_String(arr[3]),
    );
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AppError(
      kind: dco_decode_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      biliCode: dco_decode_opt_box_autoadd_i_32(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BootstrapConfig dco_decode_bootstrap_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BootstrapConfig(
      dataDir: dco_decode_String(arr[0]),
      cacheDir: dco_decode_String(arr[1]),
      logLevel: dco_decode_String(arr[2]),
    );
  }

  @protected
  AccountPublicDto dco_decode_box_autoadd_account_public_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_public_dto(raw);
  }

  @protected
  BootstrapConfig dco_decode_box_autoadd_bootstrap_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bootstrap_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  SmsLoginDto dco_decode_box_autoadd_sms_login_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sms_login_dto(raw);
  }

  @protected
  SmsSendDto dco_decode_box_autoadd_sms_send_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sms_send_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CaptchaDto dco_decode_captcha_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CaptchaDto(
      token: dco_decode_String(arr[0]),
      gt: dco_decode_String(arr[1]),
      challenge: dco_decode_String(arr[2]),
      captchaType: dco_decode_String(arr[3]),
    );
  }

  @protected
  ErrorKind dco_decode_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ErrorKind.values[raw as int];
  }

  @protected
  FeedItemDto dco_decode_feed_item_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FeedItemDto(
      aid: dco_decode_i_64(arr[0]),
      bvid: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      cover: dco_decode_String(arr[3]),
      ownerName: dco_decode_String(arr[4]),
      durationMs: dco_decode_i_64(arr[5]),
      goto: dco_decode_String(arr[6]),
    );
  }

  @protected
  HeaderDto dco_decode_header_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HeaderDto(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AccountPublicDto> dco_decode_list_account_public_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_account_public_dto).toList();
  }

  @protected
  List<FeedItemDto> dco_decode_list_feed_item_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_feed_item_dto).toList();
  }

  @protected
  List<HeaderDto> dco_decode_list_header_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_header_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StreamDto> dco_decode_list_stream_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stream_dto).toList();
  }

  @protected
  List<SubtitleTrackDto> dco_decode_list_subtitle_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_subtitle_track_dto).toList();
  }

  @protected
  List<VideoPageDto> dco_decode_list_video_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_video_page_dto).toList();
  }

  @protected
  MediaFormatDto dco_decode_media_format_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaFormatDto.values[raw as int];
  }

  @protected
  MediaSourceDto dco_decode_media_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return MediaSourceDto(
      aid: dco_decode_i_64(arr[0]),
      bvid: dco_decode_String(arr[1]),
      cid: dco_decode_i_64(arr[2]),
      format: dco_decode_media_format_dto(arr[3]),
      videos: dco_decode_list_stream_dto(arr[4]),
      audios: dco_decode_list_stream_dto(arr[5]),
      recommendedVideoId: dco_decode_String(arr[6]),
      recommendedAudioId: dco_decode_String(arr[7]),
      durationMs: dco_decode_i_64(arr[8]),
      headers: dco_decode_list_header_dto(arr[9]),
      subtitles: dco_decode_list_subtitle_track_dto(arr[10]),
      requestedQn: dco_decode_opt_box_autoadd_u_32(arr[11]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AccountPublicDto? dco_decode_opt_box_autoadd_account_public_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_account_public_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PopularFeedDto dco_decode_popular_feed_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PopularFeedDto(
      items: dco_decode_list_feed_item_dto(arr[0]),
      nextPn: dco_decode_i_32(arr[1]),
      noMore: dco_decode_bool(arr[2]),
    );
  }

  @protected
  QrPollDto dco_decode_qr_poll_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QrPollDto(
      status: dco_decode_qr_status_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      account: dco_decode_opt_box_autoadd_account_public_dto(arr[2]),
    );
  }

  @protected
  QrStartDto dco_decode_qr_start_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrStartDto(
      url: dco_decode_String(arr[0]),
      authCode: dco_decode_String(arr[1]),
    );
  }

  @protected
  QrStatusKind dco_decode_qr_status_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QrStatusKind.values[raw as int];
  }

  @protected
  RecommendFeedDto dco_decode_recommend_feed_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RecommendFeedDto(
      items: dco_decode_list_feed_item_dto(arr[0]),
      nextFreshIdx: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  SlotDto dco_decode_slot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SlotDto.values[raw as int];
  }

  @protected
  SmsLoginDto dco_decode_sms_login_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SmsLoginDto(
      cid: dco_decode_i_32(arr[0]),
      tel: dco_decode_String(arr[1]),
      code: dco_decode_String(arr[2]),
      captchaKey: dco_decode_String(arr[3]),
      loginSessionId: dco_decode_String(arr[4]),
    );
  }

  @protected
  SmsSendDto dco_decode_sms_send_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SmsSendDto(
      cid: dco_decode_i_32(arr[0]),
      tel: dco_decode_String(arr[1]),
      token: dco_decode_String(arr[2]),
      geeChallenge: dco_decode_String(arr[3]),
      geeValidate: dco_decode_String(arr[4]),
      geeSeccode: dco_decode_String(arr[5]),
      loginSessionId: dco_decode_String(arr[6]),
      localId: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  SmsSendDtoResult dco_decode_sms_send_dto_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SmsSendDtoResult(
      captchaKey: dco_decode_String(arr[0]),
      loginSessionId: dco_decode_String(arr[1]),
    );
  }

  @protected
  StreamDto dco_decode_stream_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return StreamDto(
      id: dco_decode_String(arr[0]),
      codec: dco_decode_String(arr[1]),
      bandwidth: dco_decode_u_32(arr[2]),
      width: dco_decode_opt_box_autoadd_u_32(arr[3]),
      height: dco_decode_opt_box_autoadd_u_32(arr[4]),
      fps: dco_decode_opt_box_autoadd_u_32(arr[5]),
      qualityLabel: dco_decode_String(arr[6]),
      qn: dco_decode_opt_box_autoadd_u_32(arr[7]),
      language: dco_decode_opt_String(arr[8]),
      role: dco_decode_opt_String(arr[9]),
      url: dco_decode_String(arr[10]),
      backupUrls: dco_decode_list_String(arr[11]),
    );
  }

  @protected
  SubtitleTrackDto dco_decode_subtitle_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SubtitleTrackDto(
      id: dco_decode_String(arr[0]),
      lang: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoDetailDto dco_decode_video_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return VideoDetailDto(
      aid: dco_decode_i_64(arr[0]),
      bvid: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      cover: dco_decode_String(arr[3]),
      desc: dco_decode_String(arr[4]),
      ownerMid: dco_decode_i_64(arr[5]),
      ownerName: dco_decode_String(arr[6]),
      ownerFace: dco_decode_String(arr[7]),
      pages: dco_decode_list_video_page_dto(arr[8]),
      stat: dco_decode_video_stat_dto(arr[9]),
      durationMs: dco_decode_i_64(arr[10]),
    );
  }

  @protected
  VideoPageDto dco_decode_video_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VideoPageDto(
      cid: dco_decode_i_64(arr[0]),
      page: dco_decode_i_32(arr[1]),
      part_: dco_decode_String(arr[2]),
      durationMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  VideoStatDto dco_decode_video_stat_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VideoStatDto(
      view: dco_decode_i_64(arr[0]),
      danmaku: dco_decode_i_64(arr[1]),
      reply: dco_decode_i_64(arr[2]),
      favorite: dco_decode_i_64(arr[3]),
      coin: dco_decode_i_64(arr[4]),
      share: dco_decode_i_64(arr[5]),
      like: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountPublicDto sse_decode_account_public_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_mid = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_isLogin = sse_decode_bool(deserializer);
    return AccountPublicDto(
      id: var_id,
      mid: var_mid,
      name: var_name,
      avatarUrl: var_avatarUrl,
      isLogin: var_isLogin,
    );
  }

  @protected
  ApiVersion sse_decode_api_version(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_major = sse_decode_u_32(deserializer);
    var var_minor = sse_decode_u_32(deserializer);
    var var_patch = sse_decode_u_32(deserializer);
    var var_core = sse_decode_String(deserializer);
    return ApiVersion(
      major: var_major,
      minor: var_minor,
      patch: var_patch,
      core: var_core,
    );
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_biliCode = sse_decode_opt_box_autoadd_i_32(deserializer);
    return AppError(
      kind: var_kind,
      message: var_message,
      biliCode: var_biliCode,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BootstrapConfig sse_decode_bootstrap_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dataDir = sse_decode_String(deserializer);
    var var_cacheDir = sse_decode_String(deserializer);
    var var_logLevel = sse_decode_String(deserializer);
    return BootstrapConfig(
      dataDir: var_dataDir,
      cacheDir: var_cacheDir,
      logLevel: var_logLevel,
    );
  }

  @protected
  AccountPublicDto sse_decode_box_autoadd_account_public_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_public_dto(deserializer));
  }

  @protected
  BootstrapConfig sse_decode_box_autoadd_bootstrap_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bootstrap_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  SmsLoginDto sse_decode_box_autoadd_sms_login_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sms_login_dto(deserializer));
  }

  @protected
  SmsSendDto sse_decode_box_autoadd_sms_send_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sms_send_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CaptchaDto sse_decode_captcha_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    var var_gt = sse_decode_String(deserializer);
    var var_challenge = sse_decode_String(deserializer);
    var var_captchaType = sse_decode_String(deserializer);
    return CaptchaDto(
      token: var_token,
      gt: var_gt,
      challenge: var_challenge,
      captchaType: var_captchaType,
    );
  }

  @protected
  ErrorKind sse_decode_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ErrorKind.values[inner];
  }

  @protected
  FeedItemDto sse_decode_feed_item_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_i_64(deserializer);
    var var_bvid = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_cover = sse_decode_String(deserializer);
    var var_ownerName = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_goto = sse_decode_String(deserializer);
    return FeedItemDto(
      aid: var_aid,
      bvid: var_bvid,
      title: var_title,
      cover: var_cover,
      ownerName: var_ownerName,
      durationMs: var_durationMs,
      goto: var_goto,
    );
  }

  @protected
  HeaderDto sse_decode_header_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return HeaderDto(key: var_key, value: var_value);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AccountPublicDto> sse_decode_list_account_public_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AccountPublicDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_account_public_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FeedItemDto> sse_decode_list_feed_item_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FeedItemDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_feed_item_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<HeaderDto> sse_decode_list_header_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HeaderDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_header_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StreamDto> sse_decode_list_stream_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StreamDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stream_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SubtitleTrackDto> sse_decode_list_subtitle_track_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SubtitleTrackDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_subtitle_track_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<VideoPageDto> sse_decode_list_video_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VideoPageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_video_page_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MediaFormatDto sse_decode_media_format_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaFormatDto.values[inner];
  }

  @protected
  MediaSourceDto sse_decode_media_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_i_64(deserializer);
    var var_bvid = sse_decode_String(deserializer);
    var var_cid = sse_decode_i_64(deserializer);
    var var_format = sse_decode_media_format_dto(deserializer);
    var var_videos = sse_decode_list_stream_dto(deserializer);
    var var_audios = sse_decode_list_stream_dto(deserializer);
    var var_recommendedVideoId = sse_decode_String(deserializer);
    var var_recommendedAudioId = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_headers = sse_decode_list_header_dto(deserializer);
    var var_subtitles = sse_decode_list_subtitle_track_dto(deserializer);
    var var_requestedQn = sse_decode_opt_box_autoadd_u_32(deserializer);
    return MediaSourceDto(
      aid: var_aid,
      bvid: var_bvid,
      cid: var_cid,
      format: var_format,
      videos: var_videos,
      audios: var_audios,
      recommendedVideoId: var_recommendedVideoId,
      recommendedAudioId: var_recommendedAudioId,
      durationMs: var_durationMs,
      headers: var_headers,
      subtitles: var_subtitles,
      requestedQn: var_requestedQn,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccountPublicDto? sse_decode_opt_box_autoadd_account_public_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_account_public_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PopularFeedDto sse_decode_popular_feed_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_feed_item_dto(deserializer);
    var var_nextPn = sse_decode_i_32(deserializer);
    var var_noMore = sse_decode_bool(deserializer);
    return PopularFeedDto(
      items: var_items,
      nextPn: var_nextPn,
      noMore: var_noMore,
    );
  }

  @protected
  QrPollDto sse_decode_qr_poll_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_qr_status_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_account = sse_decode_opt_box_autoadd_account_public_dto(
      deserializer,
    );
    return QrPollDto(
      status: var_status,
      message: var_message,
      account: var_account,
    );
  }

  @protected
  QrStartDto sse_decode_qr_start_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_authCode = sse_decode_String(deserializer);
    return QrStartDto(url: var_url, authCode: var_authCode);
  }

  @protected
  QrStatusKind sse_decode_qr_status_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return QrStatusKind.values[inner];
  }

  @protected
  RecommendFeedDto sse_decode_recommend_feed_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_feed_item_dto(deserializer);
    var var_nextFreshIdx = sse_decode_i_32(deserializer);
    return RecommendFeedDto(items: var_items, nextFreshIdx: var_nextFreshIdx);
  }

  @protected
  SlotDto sse_decode_slot_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SlotDto.values[inner];
  }

  @protected
  SmsLoginDto sse_decode_sms_login_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cid = sse_decode_i_32(deserializer);
    var var_tel = sse_decode_String(deserializer);
    var var_code = sse_decode_String(deserializer);
    var var_captchaKey = sse_decode_String(deserializer);
    var var_loginSessionId = sse_decode_String(deserializer);
    return SmsLoginDto(
      cid: var_cid,
      tel: var_tel,
      code: var_code,
      captchaKey: var_captchaKey,
      loginSessionId: var_loginSessionId,
    );
  }

  @protected
  SmsSendDto sse_decode_sms_send_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cid = sse_decode_i_32(deserializer);
    var var_tel = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_geeChallenge = sse_decode_String(deserializer);
    var var_geeValidate = sse_decode_String(deserializer);
    var var_geeSeccode = sse_decode_String(deserializer);
    var var_loginSessionId = sse_decode_String(deserializer);
    var var_localId = sse_decode_opt_String(deserializer);
    return SmsSendDto(
      cid: var_cid,
      tel: var_tel,
      token: var_token,
      geeChallenge: var_geeChallenge,
      geeValidate: var_geeValidate,
      geeSeccode: var_geeSeccode,
      loginSessionId: var_loginSessionId,
      localId: var_localId,
    );
  }

  @protected
  SmsSendDtoResult sse_decode_sms_send_dto_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_captchaKey = sse_decode_String(deserializer);
    var var_loginSessionId = sse_decode_String(deserializer);
    return SmsSendDtoResult(
      captchaKey: var_captchaKey,
      loginSessionId: var_loginSessionId,
    );
  }

  @protected
  StreamDto sse_decode_stream_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_bandwidth = sse_decode_u_32(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_qualityLabel = sse_decode_String(deserializer);
    var var_qn = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_role = sse_decode_opt_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_backupUrls = sse_decode_list_String(deserializer);
    return StreamDto(
      id: var_id,
      codec: var_codec,
      bandwidth: var_bandwidth,
      width: var_width,
      height: var_height,
      fps: var_fps,
      qualityLabel: var_qualityLabel,
      qn: var_qn,
      language: var_language,
      role: var_role,
      url: var_url,
      backupUrls: var_backupUrls,
    );
  }

  @protected
  SubtitleTrackDto sse_decode_subtitle_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_lang = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    return SubtitleTrackDto(
      id: var_id,
      lang: var_lang,
      label: var_label,
      url: var_url,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoDetailDto sse_decode_video_detail_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_i_64(deserializer);
    var var_bvid = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_cover = sse_decode_String(deserializer);
    var var_desc = sse_decode_String(deserializer);
    var var_ownerMid = sse_decode_i_64(deserializer);
    var var_ownerName = sse_decode_String(deserializer);
    var var_ownerFace = sse_decode_String(deserializer);
    var var_pages = sse_decode_list_video_page_dto(deserializer);
    var var_stat = sse_decode_video_stat_dto(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    return VideoDetailDto(
      aid: var_aid,
      bvid: var_bvid,
      title: var_title,
      cover: var_cover,
      desc: var_desc,
      ownerMid: var_ownerMid,
      ownerName: var_ownerName,
      ownerFace: var_ownerFace,
      pages: var_pages,
      stat: var_stat,
      durationMs: var_durationMs,
    );
  }

  @protected
  VideoPageDto sse_decode_video_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cid = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_part_ = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    return VideoPageDto(
      cid: var_cid,
      page: var_page,
      part_: var_part_,
      durationMs: var_durationMs,
    );
  }

  @protected
  VideoStatDto sse_decode_video_stat_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_view = sse_decode_i_64(deserializer);
    var var_danmaku = sse_decode_i_64(deserializer);
    var var_reply = sse_decode_i_64(deserializer);
    var var_favorite = sse_decode_i_64(deserializer);
    var var_coin = sse_decode_i_64(deserializer);
    var var_share = sse_decode_i_64(deserializer);
    var var_like = sse_decode_i_64(deserializer);
    return VideoStatDto(
      view: var_view,
      danmaku: var_danmaku,
      reply: var_reply,
      favorite: var_favorite,
      coin: var_coin,
      share: var_share,
      like: var_like,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_public_dto(
    AccountPublicDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.mid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_bool(self.isLogin, serializer);
  }

  @protected
  void sse_encode_api_version(ApiVersion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.major, serializer);
    sse_encode_u_32(self.minor, serializer);
    sse_encode_u_32(self.patch, serializer);
    sse_encode_String(self.core, serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_i_32(self.biliCode, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bootstrap_config(
    BootstrapConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dataDir, serializer);
    sse_encode_String(self.cacheDir, serializer);
    sse_encode_String(self.logLevel, serializer);
  }

  @protected
  void sse_encode_box_autoadd_account_public_dto(
    AccountPublicDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_public_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bootstrap_config(
    BootstrapConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bootstrap_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sms_login_dto(
    SmsLoginDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sms_login_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sms_send_dto(
    SmsSendDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sms_send_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_captcha_dto(CaptchaDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.gt, serializer);
    sse_encode_String(self.challenge, serializer);
    sse_encode_String(self.captchaType, serializer);
  }

  @protected
  void sse_encode_error_kind(ErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_feed_item_dto(FeedItemDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.aid, serializer);
    sse_encode_String(self.bvid, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.cover, serializer);
    sse_encode_String(self.ownerName, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_String(self.goto, serializer);
  }

  @protected
  void sse_encode_header_dto(HeaderDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_account_public_dto(
    List<AccountPublicDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_account_public_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_feed_item_dto(
    List<FeedItemDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_feed_item_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_header_dto(
    List<HeaderDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_header_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_stream_dto(
    List<StreamDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stream_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_subtitle_track_dto(
    List<SubtitleTrackDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_subtitle_track_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_video_page_dto(
    List<VideoPageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_video_page_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_media_format_dto(
    MediaFormatDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_source_dto(
    MediaSourceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.aid, serializer);
    sse_encode_String(self.bvid, serializer);
    sse_encode_i_64(self.cid, serializer);
    sse_encode_media_format_dto(self.format, serializer);
    sse_encode_list_stream_dto(self.videos, serializer);
    sse_encode_list_stream_dto(self.audios, serializer);
    sse_encode_String(self.recommendedVideoId, serializer);
    sse_encode_String(self.recommendedAudioId, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_list_header_dto(self.headers, serializer);
    sse_encode_list_subtitle_track_dto(self.subtitles, serializer);
    sse_encode_opt_box_autoadd_u_32(self.requestedQn, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_account_public_dto(
    AccountPublicDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_account_public_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_popular_feed_dto(
    PopularFeedDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_feed_item_dto(self.items, serializer);
    sse_encode_i_32(self.nextPn, serializer);
    sse_encode_bool(self.noMore, serializer);
  }

  @protected
  void sse_encode_qr_poll_dto(QrPollDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qr_status_kind(self.status, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_account_public_dto(self.account, serializer);
  }

  @protected
  void sse_encode_qr_start_dto(QrStartDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.authCode, serializer);
  }

  @protected
  void sse_encode_qr_status_kind(QrStatusKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_recommend_feed_dto(
    RecommendFeedDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_feed_item_dto(self.items, serializer);
    sse_encode_i_32(self.nextFreshIdx, serializer);
  }

  @protected
  void sse_encode_slot_dto(SlotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sms_login_dto(SmsLoginDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.cid, serializer);
    sse_encode_String(self.tel, serializer);
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.captchaKey, serializer);
    sse_encode_String(self.loginSessionId, serializer);
  }

  @protected
  void sse_encode_sms_send_dto(SmsSendDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.cid, serializer);
    sse_encode_String(self.tel, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.geeChallenge, serializer);
    sse_encode_String(self.geeValidate, serializer);
    sse_encode_String(self.geeSeccode, serializer);
    sse_encode_String(self.loginSessionId, serializer);
    sse_encode_opt_String(self.localId, serializer);
  }

  @protected
  void sse_encode_sms_send_dto_result(
    SmsSendDtoResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.captchaKey, serializer);
    sse_encode_String(self.loginSessionId, serializer);
  }

  @protected
  void sse_encode_stream_dto(StreamDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_u_32(self.bandwidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_u_32(self.fps, serializer);
    sse_encode_String(self.qualityLabel, serializer);
    sse_encode_opt_box_autoadd_u_32(self.qn, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.role, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_list_String(self.backupUrls, serializer);
  }

  @protected
  void sse_encode_subtitle_track_dto(
    SubtitleTrackDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.lang, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.url, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_detail_dto(
    VideoDetailDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.aid, serializer);
    sse_encode_String(self.bvid, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.cover, serializer);
    sse_encode_String(self.desc, serializer);
    sse_encode_i_64(self.ownerMid, serializer);
    sse_encode_String(self.ownerName, serializer);
    sse_encode_String(self.ownerFace, serializer);
    sse_encode_list_video_page_dto(self.pages, serializer);
    sse_encode_video_stat_dto(self.stat, serializer);
    sse_encode_i_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_video_page_dto(VideoPageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.cid, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_String(self.part_, serializer);
    sse_encode_i_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_video_stat_dto(VideoStatDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.view, serializer);
    sse_encode_i_64(self.danmaku, serializer);
    sse_encode_i_64(self.reply, serializer);
    sse_encode_i_64(self.favorite, serializer);
    sse_encode_i_64(self.coin, serializer);
    sse_encode_i_64(self.share, serializer);
    sse_encode_i_64(self.like, serializer);
  }
}
