#include "desktop_compositor_blur.h"

#include <glib.h>

#ifdef GDK_WINDOWING_X11
#include <X11/Xatom.h>
#include <X11/Xlib.h>
#include <gdk/gdkx.h>
#endif

#ifdef GDK_WINDOWING_WAYLAND
#include <gdk/gdkwayland.h>
#include <wayland-client.h>

// Generated by wayland-scanner (see runner/CMakeLists.txt).
#include "ext-background-effect-v1-client-protocol.h"
#endif

#ifdef GDK_WINDOWING_X11
// Empty property value ⇒ blur the entire window (KWin convention).
static void request_blur_x11(GdkWindow* gdk_window) {
  if (gdk_window == nullptr || !GDK_IS_X11_WINDOW(gdk_window)) {
    return;
  }

  Display* display = GDK_WINDOW_XDISPLAY(gdk_window);
  Window xid = GDK_WINDOW_XID(gdk_window);
  if (display == nullptr || xid == None) {
    return;
  }

  Atom atom = XInternAtom(display, "_KDE_NET_WM_BLUR_BEHIND_REGION", False);
  if (atom == None) {
    return;
  }

  XChangeProperty(display, xid, atom, XA_CARDINAL, 32, PropModeReplace,
                  nullptr, 0);
  XFlush(display);
  g_debug("nextpili: X11 compositor blur-behind requested");
}
#endif

#ifdef GDK_WINDOWING_WAYLAND
// Persistent Wayland state: effect object is 1:1 with wl_surface (protocol
// error if created twice). Region is updated on resize.
struct WaylandBlurState {
  wl_display* display = nullptr;
  wl_registry* registry = nullptr;
  wl_compositor* compositor = nullptr;
  ext_background_effect_manager_v1* manager = nullptr;
  ext_background_effect_surface_v1* effect = nullptr;
  wl_surface* surface = nullptr;
  uint32_t capabilities = 0;
  bool registry_done = false;
  int last_w = -1;
  int last_h = -1;
};

static WaylandBlurState g_wl;

static void on_manager_capabilities(void* data,
                                    ext_background_effect_manager_v1* /*manager*/,
                                    uint32_t flags) {
  auto* state = static_cast<WaylandBlurState*>(data);
  state->capabilities = flags;
}

static const ext_background_effect_manager_v1_listener kManagerListener = {
    on_manager_capabilities,
};

static void on_registry_global(void* data,
                               wl_registry* registry,
                               uint32_t name,
                               const char* interface,
                               uint32_t version) {
  auto* state = static_cast<WaylandBlurState*>(data);
  if (g_strcmp0(interface, wl_compositor_interface.name) == 0) {
    state->compositor = static_cast<wl_compositor*>(wl_registry_bind(
        registry, name, &wl_compositor_interface,
        version < 4 ? version : 4));
  } else if (g_strcmp0(interface,
                       ext_background_effect_manager_v1_interface.name) == 0) {
    const uint32_t ver = version < 1 ? version : 1;
    state->manager =
        static_cast<ext_background_effect_manager_v1*>(wl_registry_bind(
            registry, name, &ext_background_effect_manager_v1_interface, ver));
    if (state->manager != nullptr) {
      ext_background_effect_manager_v1_add_listener(state->manager,
                                                    &kManagerListener, state);
    }
  }
}

static void on_registry_global_remove(void* /*data*/,
                                      wl_registry* /*registry*/,
                                      uint32_t /*name*/) {}

static const wl_registry_listener kRegistryListener = {
    on_registry_global,
    on_registry_global_remove,
};

static bool ensure_wayland_globals(wl_display* display) {
  if (g_wl.registry_done && g_wl.display == display) {
    return g_wl.manager != nullptr && g_wl.compositor != nullptr;
  }

  // New display connection (rare) — drop cached objects.
  if (g_wl.effect != nullptr) {
    ext_background_effect_surface_v1_destroy(g_wl.effect);
    g_wl.effect = nullptr;
  }
  if (g_wl.manager != nullptr) {
    ext_background_effect_manager_v1_destroy(g_wl.manager);
    g_wl.manager = nullptr;
  }
  if (g_wl.compositor != nullptr) {
    wl_compositor_destroy(g_wl.compositor);
    g_wl.compositor = nullptr;
  }
  if (g_wl.registry != nullptr) {
    wl_registry_destroy(g_wl.registry);
    g_wl.registry = nullptr;
  }

  g_wl = WaylandBlurState{};
  g_wl.display = display;
  g_wl.registry = wl_display_get_registry(display);
  if (g_wl.registry == nullptr) {
    return false;
  }

  wl_registry_add_listener(g_wl.registry, &kRegistryListener, &g_wl);
  // Roundtrip: bind globals + receive capabilities event.
  wl_display_roundtrip(display);
  g_wl.registry_done = true;

  if (g_wl.manager == nullptr) {
    g_debug("nextpili: compositor has no ext-background-effect-v1");
    return false;
  }
  if (g_wl.compositor == nullptr) {
    g_debug("nextpili: missing wl_compositor for blur region");
    return false;
  }
  if ((g_wl.capabilities &
       EXT_BACKGROUND_EFFECT_MANAGER_V1_CAPABILITY_BLUR) == 0) {
    g_debug("nextpili: ext-background-effect-v1 present but blur capability off");
    return false;
  }
  return true;
}

// Protocol: empty region = no blur; null region = remove effect.
// Full-window blur requires an explicit surface-local region covering size.
static void set_full_surface_blur_region(int width, int height) {
  if (g_wl.effect == nullptr || g_wl.compositor == nullptr) {
    return;
  }
  if (width <= 0 || height <= 0) {
    return;
  }
  if (width == g_wl.last_w && height == g_wl.last_h) {
    return;
  }

  wl_region* region = wl_compositor_create_region(g_wl.compositor);
  if (region == nullptr) {
    return;
  }
  wl_region_add(region, 0, 0, width, height);
  ext_background_effect_surface_v1_set_blur_region(g_wl.effect, region);
  wl_region_destroy(region);
  g_wl.last_w = width;
  g_wl.last_h = height;
  // Double-buffered; applied on next surface commit (GTK commits every frame).
  wl_display_flush(g_wl.display);
}

static void request_blur_wayland(GdkWindow* gdk_window) {
  if (gdk_window == nullptr || !GDK_IS_WAYLAND_WINDOW(gdk_window)) {
    return;
  }

  wl_display* display = gdk_wayland_display_get_wl_display(
      gdk_window_get_display(gdk_window));
  wl_surface* surface = gdk_wayland_window_get_wl_surface(gdk_window);
  if (display == nullptr || surface == nullptr) {
    return;
  }

  if (!ensure_wayland_globals(display)) {
    return;
  }

  // One effect object per surface (protocol error if recreated).
  if (g_wl.effect == nullptr || g_wl.surface != surface) {
    if (g_wl.effect != nullptr) {
      ext_background_effect_surface_v1_destroy(g_wl.effect);
      g_wl.effect = nullptr;
      g_wl.last_w = -1;
      g_wl.last_h = -1;
    }
    g_wl.surface = surface;
    g_wl.effect = ext_background_effect_manager_v1_get_background_effect(
        g_wl.manager, surface);
    if (g_wl.effect == nullptr) {
      g_warning("nextpili: get_background_effect failed");
      return;
    }
    g_debug("nextpili: Wayland ext-background-effect-v1 attached");
  }

  const int width = gdk_window_get_width(gdk_window);
  const int height = gdk_window_get_height(gdk_window);
  set_full_surface_blur_region(width, height);
}
#endif

void nextpili_request_compositor_blur(GtkWindow* window) {
  if (window == nullptr) {
    return;
  }

  GtkWidget* widget = GTK_WIDGET(window);
  if (!gtk_widget_get_realized(widget)) {
    return;
  }

  GdkWindow* gdk_window = gtk_widget_get_window(widget);
  if (gdk_window == nullptr) {
    return;
  }

  GdkDisplay* display = gdk_window_get_display(gdk_window);
#ifdef GDK_WINDOWING_WAYLAND
  if (GDK_IS_WAYLAND_DISPLAY(display)) {
    request_blur_wayland(gdk_window);
    return;
  }
#endif
#ifdef GDK_WINDOWING_X11
  if (GDK_IS_X11_DISPLAY(display)) {
    request_blur_x11(gdk_window);
    return;
  }
#endif
  (void)display;
}
