// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../auth_service.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_local_id`

/// Start TV/HD QR login. Prefer only on desktop / tablet UI surfaces.
///
/// `local_id` may be empty (defaults to device buvid / "0").
Future<QrStartDto> loginQrStart({String? localId}) =>
    RustLib.instance.api.crateApiAuthLoginQrStart(localId: localId);

/// Poll QR login once. Caller should interval ~1.5–2s until confirmed/expired.
Future<QrPollDto> loginQrPoll({required String authCode, String? localId}) =>
    RustLib.instance.api.crateApiAuthLoginQrPoll(
      authCode: authCode,
      localId: localId,
    );

/// Fetch geetest parameters for SMS login.
Future<CaptchaDto> loginCaptcha() =>
    RustLib.instance.api.crateApiAuthLoginCaptcha();

/// Generate a fresh SMS login session id (uuid without dashes).
String newLoginSessionId() =>
    RustLib.instance.api.crateApiAuthNewLoginSessionId();

/// Send SMS verification code after captcha is solved.
Future<SmsSendDtoResult> loginSmsSend({required SmsSendDto req}) =>
    RustLib.instance.api.crateApiAuthLoginSmsSend(req: req);

/// Complete SMS login.
Future<AccountPublicDto> loginSms({required SmsLoginDto req}) =>
    RustLib.instance.api.crateApiAuthLoginSms(req: req);

/// List known accounts (no secrets).
List<AccountPublicDto> listAccounts() =>
    RustLib.instance.api.crateApiAuthListAccounts();

/// Remove an account. If `account_id` is null, removes active main.
void logout({String? accountId}) =>
    RustLib.instance.api.crateApiAuthLogout(accountId: accountId);

/// Bind an account to a routing slot.
void setAccountSlot({required SlotDto slot, String? accountId}) => RustLib
    .instance
    .api
    .crateApiAuthSetAccountSlot(slot: slot, accountId: accountId);

/// Device buvid3 (always available after bootstrap).
String deviceBuvid3() => RustLib.instance.api.crateApiAuthDeviceBuvid3();
