// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_main`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Follow dynamics feed (main slot · Cookie).
///
/// First page: `offset = ""`. Subsequent: pass `next_offset`.
/// `type_filter`: `all` / `video` / `pgc` / `article` (empty → `all`).
/// `page`: 1-based page counter (web still expects it; cursor is `offset`).
Future<DynamicPageDto> dynamicsFeed({
  required String offset,
  required String typeFilter,
  required int page,
}) => RustLib.instance.api.crateApiDynamicsDynamicsFeed(
  offset: offset,
  typeFilter: typeFilter,
  page: page,
);

/// One dynamic card for the UI.
class DynamicItemDto {
  final String id;

  /// e.g. `DYNAMIC_TYPE_AV`
  final String typeTag;
  final PlatformInt64 authorMid;
  final String authorName;
  final String authorFace;
  final PlatformInt64 pubTsMs;
  final String text;
  final String title;
  final String cover;
  final PlatformInt64 aid;
  final String bvid;
  final PlatformInt64 durationMs;
  final PlatformInt64 likeCount;
  final PlatformInt64 commentCount;
  final PlatformInt64 repostCount;

  const DynamicItemDto({
    required this.id,
    required this.typeTag,
    required this.authorMid,
    required this.authorName,
    required this.authorFace,
    required this.pubTsMs,
    required this.text,
    required this.title,
    required this.cover,
    required this.aid,
    required this.bvid,
    required this.durationMs,
    required this.likeCount,
    required this.commentCount,
    required this.repostCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      typeTag.hashCode ^
      authorMid.hashCode ^
      authorName.hashCode ^
      authorFace.hashCode ^
      pubTsMs.hashCode ^
      text.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      aid.hashCode ^
      bvid.hashCode ^
      durationMs.hashCode ^
      likeCount.hashCode ^
      commentCount.hashCode ^
      repostCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DynamicItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          typeTag == other.typeTag &&
          authorMid == other.authorMid &&
          authorName == other.authorName &&
          authorFace == other.authorFace &&
          pubTsMs == other.pubTsMs &&
          text == other.text &&
          title == other.title &&
          cover == other.cover &&
          aid == other.aid &&
          bvid == other.bvid &&
          durationMs == other.durationMs &&
          likeCount == other.likeCount &&
          commentCount == other.commentCount &&
          repostCount == other.repostCount;
}

/// Cursor page of dynamics.
class DynamicPageDto {
  final List<DynamicItemDto> items;
  final String nextOffset;
  final bool hasMore;
  final String updateBaseline;
  final int updateNum;

  const DynamicPageDto({
    required this.items,
    required this.nextOffset,
    required this.hasMore,
    required this.updateBaseline,
    required this.updateNum,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      nextOffset.hashCode ^
      hasMore.hashCode ^
      updateBaseline.hashCode ^
      updateNum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DynamicPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextOffset == other.nextOffset &&
          hasMore == other.hasMore &&
          updateBaseline == other.updateBaseline &&
          updateNum == other.updateNum;
}
