// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_empty`, `main_account`, `refresh_relation_soft`, `require_main`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Current engagement flags. Requires login; empty defaults when unauthenticated.
Future<ArchiveRelationDto> videoRelation({
  required PlatformInt64 aid,
  required String bvid,
}) =>
    RustLib.instance.api.crateApiEngagementVideoRelation(aid: aid, bvid: bvid);

/// Toggle like. `like=true` 点赞, `false` 取消.
Future<ArchiveRelationDto> videoLike({
  required PlatformInt64 aid,
  required String bvid,
  required bool like,
}) => RustLib.instance.api.crateApiEngagementVideoLike(
  aid: aid,
  bvid: bvid,
  like: like,
);

/// Cast coins. `multiply` clamped to 1..=2. Optionally like at the same time.
Future<ArchiveRelationDto> videoCoin({
  required PlatformInt64 aid,
  required String bvid,
  required int multiply,
  required bool alsoLike,
}) => RustLib.instance.api.crateApiEngagementVideoCoin(
  aid: aid,
  bvid: bvid,
  multiply: multiply,
  alsoLike: alsoLike,
);

/// Favorite into the default folder, or unfav-all when `favorite=false`.
Future<ArchiveRelationDto> videoFavorite({
  required PlatformInt64 aid,
  required String bvid,
  required bool favorite,
}) => RustLib.instance.api.crateApiEngagementVideoFavorite(
  aid: aid,
  bvid: bvid,
  favorite: favorite,
);

/// Add / remove an archive from specific favorite folders (`media_id`s).
///
/// Empty both lists is an error. Prefer this for multi-folder picker; short-press
/// toggle still uses [`video_favorite`].
Future<ArchiveRelationDto> videoFavoriteDeal({
  required PlatformInt64 aid,
  required String bvid,
  required Int64List addMediaIds,
  required Int64List delMediaIds,
}) => RustLib.instance.api.crateApiEngagementVideoFavoriteDeal(
  aid: aid,
  bvid: bvid,
  addMediaIds: addMediaIds,
  delMediaIds: delMediaIds,
);

/// Follow / unfollow UP (`mid`).
Future<void> relationFollow({
  required PlatformInt64 mid,
  required bool follow,
}) => RustLib.instance.api.crateApiEngagementRelationFollow(
  mid: mid,
  follow: follow,
);

/// Viewer relationship to an archive (+ follow flag for its UP).
class ArchiveRelationDto {
  final bool liked;
  final bool disliked;

  /// Coins already cast (0..=2).
  final int coin;
  final bool favorited;
  final bool following;

  const ArchiveRelationDto({
    required this.liked,
    required this.disliked,
    required this.coin,
    required this.favorited,
    required this.following,
  });

  @override
  int get hashCode =>
      liked.hashCode ^
      disliked.hashCode ^
      coin.hashCode ^
      favorited.hashCode ^
      following.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveRelationDto &&
          runtimeType == other.runtimeType &&
          liked == other.liked &&
          disliked == other.disliked &&
          coin == other.coin &&
          favorited == other.favorited &&
          following == other.following;
}
