// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_wbi`, `map_item`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Home recommend feed (WBI · recommend slot).
///
/// `fresh_idx`: refresh counter, start at `0` or `1`, then use `next_fresh_idx`.
/// `ps`: page size (default 12 if 0).
Future<RecommendFeedDto> feedRecommend({
  required int freshIdx,
  required int ps,
}) =>
    RustLib.instance.api.crateApiFeedFeedRecommend(freshIdx: freshIdx, ps: ps);

/// Popular feed (paginated).
///
/// `pn`: page number starting at 1; `ps`: page size (default 20 if 0).
Future<PopularFeedDto> feedPopular({required int pn, required int ps}) =>
    RustLib.instance.api.crateApiFeedFeedPopular(pn: pn, ps: ps);

/// Primary partition list for home 分区导航 (static main tids; ranking only).
Future<List<RegionDto>> feedRegions() =>
    RustLib.instance.api.crateApiFeedFeedRegions();

/// Partition ranking (WBI · recommend slot).
///
/// `rid`: primary partition tid; `0` = site-wide.
/// `rank_type`: `all` | `rookie` | `origin` (empty → `all`).
Future<RankingFeedDto> feedRanking({
  required int rid,
  required String rankType,
}) =>
    RustLib.instance.api.crateApiFeedFeedRanking(rid: rid, rankType: rankType);

/// Single card in home feed.
class FeedItemDto {
  final PlatformInt64 aid;
  final String bvid;
  final String title;
  final String cover;
  final String ownerName;
  final PlatformInt64 durationMs;
  final String goto;

  const FeedItemDto({
    required this.aid,
    required this.bvid,
    required this.title,
    required this.cover,
    required this.ownerName,
    required this.durationMs,
    required this.goto,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      ownerName.hashCode ^
      durationMs.hashCode ^
      goto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedItemDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          title == other.title &&
          cover == other.cover &&
          ownerName == other.ownerName &&
          durationMs == other.durationMs &&
          goto == other.goto;
}

/// Popular page payload.
class PopularFeedDto {
  final List<FeedItemDto> items;
  final int nextPn;
  final bool noMore;

  const PopularFeedDto({
    required this.items,
    required this.nextPn,
    required this.noMore,
  });

  @override
  int get hashCode => items.hashCode ^ nextPn.hashCode ^ noMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PopularFeedDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPn == other.nextPn &&
          noMore == other.noMore;
}

/// Partition ranking payload (`ranking/v2`; typically ≤100 items, no paging).
class RankingFeedDto {
  final List<FeedItemDto> items;
  final String note;

  const RankingFeedDto({required this.items, required this.note});

  @override
  int get hashCode => items.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RankingFeedDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          note == other.note;
}

/// Recommend page payload.
class RecommendFeedDto {
  final List<FeedItemDto> items;

  /// Pass this as `fresh_idx` on the next call (starts at 0/1).
  final int nextFreshIdx;

  const RecommendFeedDto({required this.items, required this.nextFreshIdx});

  @override
  int get hashCode => items.hashCode ^ nextFreshIdx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendFeedDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextFreshIdx == other.nextFreshIdx;
}

/// One primary partition entry for home 分区导航 (text labels only).
class RegionDto {
  final int rid;

  /// Stable key for l10n (e.g. `all`, `douga`, `music`). Empty for unknown.
  final String key;

  /// Chinese display name from taxonomy (Flutter may prefer ARB by `key`).
  final String name;

  const RegionDto({required this.rid, required this.key, required this.name});

  @override
  int get hashCode => rid.hashCode ^ key.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegionDto &&
          runtimeType == other.runtimeType &&
          rid == other.rid &&
          key == other.key &&
          name == other.name;
}
