// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_wbi`, `map_item`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Home recommend feed (WBI · recommend slot).
///
/// `fresh_idx`: refresh counter, start at `0` or `1`, then use `next_fresh_idx`.
/// `ps`: page size (default 12 if 0).
Future<RecommendFeedDto> feedRecommend({
  required int freshIdx,
  required int ps,
}) =>
    RustLib.instance.api.crateApiFeedFeedRecommend(freshIdx: freshIdx, ps: ps);

/// Popular feed (paginated).
///
/// `pn`: page number starting at 1; `ps`: page size (default 20 if 0).
Future<PopularFeedDto> feedPopular({required int pn, required int ps}) =>
    RustLib.instance.api.crateApiFeedFeedPopular(pn: pn, ps: ps);

/// Single card in home feed.
class FeedItemDto {
  final PlatformInt64 aid;
  final String bvid;
  final String title;
  final String cover;
  final String ownerName;
  final PlatformInt64 durationMs;
  final String goto;

  const FeedItemDto({
    required this.aid,
    required this.bvid,
    required this.title,
    required this.cover,
    required this.ownerName,
    required this.durationMs,
    required this.goto,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      ownerName.hashCode ^
      durationMs.hashCode ^
      goto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedItemDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          title == other.title &&
          cover == other.cover &&
          ownerName == other.ownerName &&
          durationMs == other.durationMs &&
          goto == other.goto;
}

/// Popular page payload.
class PopularFeedDto {
  final List<FeedItemDto> items;
  final int nextPn;
  final bool noMore;

  const PopularFeedDto({
    required this.items,
    required this.nextPn,
    required this.noMore,
  });

  @override
  int get hashCode => items.hashCode ^ nextPn.hashCode ^ noMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PopularFeedDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPn == other.nextPn &&
          noMore == other.noMore;
}

/// Recommend page payload.
class RecommendFeedDto {
  final List<FeedItemDto> items;

  /// Pass this as `fresh_idx` on the next call (starts at 0/1).
  final int nextFreshIdx;

  const RecommendFeedDto({required this.items, required this.nextFreshIdx});

  @override
  int get hashCode => items.hashCode ^ nextFreshIdx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendFeedDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextFreshIdx == other.nextFreshIdx;
}
