// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'video.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_wbi`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Web live room list (`/room/v3/Area/getRoomList`). Optional login.
Future<LiveRecommendPageDto> liveRecommend({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiLiveLiveRecommend(
  page: page,
  pageSize: pageSize,
);

/// Room metadata (`getH5InfoByRoom`). Optional login.
Future<LiveRoomDto> liveRoom({required PlatformInt64 roomId}) =>
    RustLib.instance.api.crateApiLiveLiveRoom(roomId: roomId);

/// Resolve live playurl → [`MediaSourceDto`] (segment/muxed FLV or HLS).
///
/// - `room_id`: real room id
/// - `qn`: preferred quality (0 = 原画 10000)
///
/// `MediaSourceDto.cid` carries `room_id`; `aid`/`bvid` are empty.
Future<MediaSourceDto> livePlayUrl({
  required PlatformInt64 roomId,
  required int qn,
}) => RustLib.instance.api.crateApiLiveLivePlayUrl(roomId: roomId, qn: qn);

/// Recent room chat (history REST). Optional login.
Future<List<LiveDanmakuItemDto>> liveDmHistory({
  required PlatformInt64 roomId,
}) => RustLib.instance.api.crateApiLiveLiveDmHistory(roomId: roomId);

/// Send live room danmaku. Requires login.
Future<void> liveSendMsg({
  required PlatformInt64 roomId,
  required String msg,
}) => RustLib.instance.api.crateApiLiveLiveSendMsg(roomId: roomId, msg: msg);

/// One live chat line (history REST; WS later).
class LiveDanmakuItemDto {
  final PlatformInt64 uid;
  final String uname;
  final String text;
  final PlatformInt64 timelineMs;

  const LiveDanmakuItemDto({
    required this.uid,
    required this.uname,
    required this.text,
    required this.timelineMs,
  });

  @override
  int get hashCode =>
      uid.hashCode ^ uname.hashCode ^ text.hashCode ^ timelineMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveDanmakuItemDto &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          uname == other.uname &&
          text == other.text &&
          timelineMs == other.timelineMs;
}

/// Paginated live recommend page.
class LiveRecommendPageDto {
  final List<LiveRoomCardDto> items;
  final int page;
  final bool hasMore;

  const LiveRecommendPageDto({
    required this.items,
    required this.page,
    required this.hasMore,
  });

  @override
  int get hashCode => items.hashCode ^ page.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRecommendPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          hasMore == other.hasMore;
}

/// One live room card for the recommend grid.
class LiveRoomCardDto {
  final PlatformInt64 roomId;
  final PlatformInt64 uid;
  final String title;
  final String uname;
  final String face;
  final String cover;
  final PlatformInt64 online;
  final String areaName;

  const LiveRoomCardDto({
    required this.roomId,
    required this.uid,
    required this.title,
    required this.uname,
    required this.face,
    required this.cover,
    required this.online,
    required this.areaName,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      uid.hashCode ^
      title.hashCode ^
      uname.hashCode ^
      face.hashCode ^
      cover.hashCode ^
      online.hashCode ^
      areaName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRoomCardDto &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          uid == other.uid &&
          title == other.title &&
          uname == other.uname &&
          face == other.face &&
          cover == other.cover &&
          online == other.online &&
          areaName == other.areaName;
}

/// Room metadata for the watch page.
class LiveRoomDto {
  final PlatformInt64 roomId;
  final PlatformInt64 shortId;
  final PlatformInt64 uid;
  final String title;
  final String cover;
  final String uname;
  final String face;
  final PlatformInt64 online;

  /// 0 offline · 1 live · 2 round.
  final int liveStatus;
  final String areaName;

  const LiveRoomDto({
    required this.roomId,
    required this.shortId,
    required this.uid,
    required this.title,
    required this.cover,
    required this.uname,
    required this.face,
    required this.online,
    required this.liveStatus,
    required this.areaName,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      shortId.hashCode ^
      uid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      uname.hashCode ^
      face.hashCode ^
      online.hashCode ^
      liveStatus.hashCode ^
      areaName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRoomDto &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          shortId == other.shortId &&
          uid == other.uid &&
          title == other.title &&
          cover == other.cover &&
          uname == other.uname &&
          face == other.face &&
          online == other.online &&
          liveStatus == other.liveStatus &&
          areaName == other.areaName;
}
