// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'video.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_wbi`, `map_source`, `map_stream`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// PGC web rank (`/pgc/web/rank/list`, WBI).
///
/// `season_type`: 1 番剧 · 2 电影 · 3 纪录片 · 4 国创 · 5 电视剧 · 7 综艺.
/// `day`: 3 | 7 (0 → 3).
Future<PgcRankPageDto> pgcRank({required int seasonType, required int day}) =>
    RustLib.instance.api.crateApiPgcPgcRank(seasonType: seasonType, day: day);

/// Season detail by `season_id` and/or `ep_id` (at least one > 0).
Future<PgcSeasonDto> pgcSeason({
  required PlatformInt64 seasonId,
  required PlatformInt64 epId,
}) => RustLib.instance.api.crateApiPgcPgcSeason(seasonId: seasonId, epId: epId);

/// PGC playurl → [`MediaSourceDto`].
///
/// - `ep_id`: episode id
/// - `cid`: episode cid
/// - `qn`: preferred quality (0 = store preferred / 80)
/// - `fnval`: dash mask (0 = default)
Future<MediaSourceDto> pgcPlayUrl({
  required PlatformInt64 epId,
  required PlatformInt64 cid,
  required int qn,
  required int fnval,
}) => RustLib.instance.api.crateApiPgcPgcPlayUrl(
  epId: epId,
  cid: cid,
  qn: qn,
  fnval: fnval,
);

/// Episode row.
class PgcEpisodeDto {
  final PlatformInt64 epId;
  final PlatformInt64 aid;
  final String bvid;
  final PlatformInt64 cid;
  final String title;
  final String longTitle;
  final String cover;
  final PlatformInt64 durationMs;
  final String badge;

  const PgcEpisodeDto({
    required this.epId,
    required this.aid,
    required this.bvid,
    required this.cid,
    required this.title,
    required this.longTitle,
    required this.cover,
    required this.durationMs,
    required this.badge,
  });

  @override
  int get hashCode =>
      epId.hashCode ^
      aid.hashCode ^
      bvid.hashCode ^
      cid.hashCode ^
      title.hashCode ^
      longTitle.hashCode ^
      cover.hashCode ^
      durationMs.hashCode ^
      badge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgcEpisodeDto &&
          runtimeType == other.runtimeType &&
          epId == other.epId &&
          aid == other.aid &&
          bvid == other.bvid &&
          cid == other.cid &&
          title == other.title &&
          longTitle == other.longTitle &&
          cover == other.cover &&
          durationMs == other.durationMs &&
          badge == other.badge;
}

/// Rank list card.
class PgcRankItemDto {
  final PlatformInt64 seasonId;
  final String title;
  final String cover;
  final String badge;
  final String indexShow;
  final String rating;
  final int order;

  const PgcRankItemDto({
    required this.seasonId,
    required this.title,
    required this.cover,
    required this.badge,
    required this.indexShow,
    required this.rating,
    required this.order,
  });

  @override
  int get hashCode =>
      seasonId.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      badge.hashCode ^
      indexShow.hashCode ^
      rating.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgcRankItemDto &&
          runtimeType == other.runtimeType &&
          seasonId == other.seasonId &&
          title == other.title &&
          cover == other.cover &&
          badge == other.badge &&
          indexShow == other.indexShow &&
          rating == other.rating &&
          order == other.order;
}

/// Rank page.
class PgcRankPageDto {
  final List<PgcRankItemDto> items;
  final int seasonType;
  final String note;

  const PgcRankPageDto({
    required this.items,
    required this.seasonType,
    required this.note,
  });

  @override
  int get hashCode => items.hashCode ^ seasonType.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgcRankPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          seasonType == other.seasonType &&
          note == other.note;
}

/// Season detail.
class PgcSeasonDto {
  final PlatformInt64 seasonId;
  final String seasonTitle;
  final String title;
  final String cover;
  final String evaluate;
  final int seasonType;
  final String typeName;
  final String ratingScore;
  final List<PgcEpisodeDto> episodes;
  final PlatformInt64 defaultEpId;

  const PgcSeasonDto({
    required this.seasonId,
    required this.seasonTitle,
    required this.title,
    required this.cover,
    required this.evaluate,
    required this.seasonType,
    required this.typeName,
    required this.ratingScore,
    required this.episodes,
    required this.defaultEpId,
  });

  @override
  int get hashCode =>
      seasonId.hashCode ^
      seasonTitle.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      evaluate.hashCode ^
      seasonType.hashCode ^
      typeName.hashCode ^
      ratingScore.hashCode ^
      episodes.hashCode ^
      defaultEpId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgcSeasonDto &&
          runtimeType == other.runtimeType &&
          seasonId == other.seasonId &&
          seasonTitle == other.seasonTitle &&
          title == other.title &&
          cover == other.cover &&
          evaluate == other.evaluate &&
          seasonType == other.seasonType &&
          typeName == other.typeName &&
          ratingScore == other.ratingScore &&
          episodes == other.episodes &&
          defaultEpId == other.defaultEpId;
}
