// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_wbi`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Search suggestions for `term` (recommend slot when available).
Future<SearchSuggestDto> searchSuggest({required String term}) =>
    RustLib.instance.api.crateApiSearchSearchSuggest(term: term);

/// Classification search: `search_type=video` (WBI · recommend slot).
///
/// `page` starts at 1. Empty keyword → `InvalidArgument`.
Future<SearchVideoPageDto> searchVideo({
  required String keyword,
  required int page,
}) => RustLib.instance.api.crateApiSearchSearchVideo(
  keyword: keyword,
  page: page,
);

/// Typeahead suggestions.
class SearchSuggestDto {
  final List<String> terms;

  const SearchSuggestDto({required this.terms});

  @override
  int get hashCode => terms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchSuggestDto &&
          runtimeType == other.runtimeType &&
          terms == other.terms;
}

/// Single video hit for search results.
class SearchVideoItemDto {
  final PlatformInt64 aid;
  final String bvid;
  final String title;
  final String cover;
  final String ownerName;
  final PlatformInt64 durationMs;
  final PlatformInt64 play;

  const SearchVideoItemDto({
    required this.aid,
    required this.bvid,
    required this.title,
    required this.cover,
    required this.ownerName,
    required this.durationMs,
    required this.play,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      ownerName.hashCode ^
      durationMs.hashCode ^
      play.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchVideoItemDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          title == other.title &&
          cover == other.cover &&
          ownerName == other.ownerName &&
          durationMs == other.durationMs &&
          play == other.play;
}

/// Paginated video search page.
class SearchVideoPageDto {
  final List<SearchVideoItemDto> items;
  final int page;
  final int numPages;
  final PlatformInt64 numResults;

  const SearchVideoPageDto({
    required this.items,
    required this.page,
    required this.numPages,
    required this.numResults,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ numPages.hashCode ^ numResults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchVideoPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          numPages == other.numPages &&
          numResults == other.numResults;
}
