// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_settings`, `validate_proxy_url`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Read current settings from store.
SettingsDto getSettings() => RustLib.instance.api.crateApiSettingsGetSettings();

/// Patch settings.
///
/// - `preferred_qn`: `None` keeps previous; `Some(0)` rejects; otherwise persists.
/// - `proxy`: `None` keeps previous; `Some("")` clears; non-empty sets and rebuilds HTTP client.
/// - `locale`: `None` keeps previous; `Some("")` clears; otherwise sets.
SettingsDto updateSettings({int? preferredQn, String? proxy, String? locale}) =>
    RustLib.instance.api.crateApiSettingsUpdateSettings(
      preferredQn: preferredQn,
      proxy: proxy,
      locale: locale,
    );

/// Protocol / playback settings (Rust store).
class SettingsDto {
  /// Preferred video quality (Bilibili qn). `0` is invalid; default is 80 (1080P).
  final int preferredQn;

  /// Optional HTTP(S) proxy URL, e.g. `http://127.0.0.1:7890`.
  final String? proxy;

  /// UI language preference (optional).
  final String? locale;

  const SettingsDto({required this.preferredQn, this.proxy, this.locale});

  @override
  int get hashCode => preferredQn.hashCode ^ proxy.hashCode ^ locale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          preferredQn == other.preferredQn &&
          proxy == other.proxy &&
          locale == other.locale;
}
