// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Health check for FRB / native library linkage.
String ping() => RustLib.instance.api.crateApiSimplePing();

/// Return FFI compatibility version.
ApiVersion apiVersion() => RustLib.instance.api.crateApiSimpleApiVersion();

/// Initialize process-global core (store, http client, accounts).
Future<void> bootstrap({required BootstrapConfig config}) =>
    RustLib.instance.api.crateApiSimpleBootstrap(config: config);

/// FFI API version payload.
class ApiVersion {
  final int major;
  final int minor;
  final int patch;

  /// Core package version / build id.
  final String core;

  const ApiVersion({
    required this.major,
    required this.minor,
    required this.patch,
    required this.core,
  });

  @override
  int get hashCode =>
      major.hashCode ^ minor.hashCode ^ patch.hashCode ^ core.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVersion &&
          runtimeType == other.runtimeType &&
          major == other.major &&
          minor == other.minor &&
          patch == other.patch &&
          core == other.core;
}

/// Runtime bootstrap configuration from Flutter.
class BootstrapConfig {
  final String dataDir;
  final String cacheDir;
  final String logLevel;

  const BootstrapConfig({
    required this.dataDir,
    required this.cacheDir,
    required this.logLevel,
  });

  @override
  int get hashCode => dataDir.hashCode ^ cacheDir.hashCode ^ logLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BootstrapConfig &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          cacheDir == other.cacheDir &&
          logLevel == other.logLevel;
}
