// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_wbi`, `require_main`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Main-floor comment list (REST `/x/v2/reply/main`).
///
/// - `oid`: video **aid**
/// - `type_`: subject type (`0` → video `1`)
/// - `mode`: `0` → heat `3`; `2` time; `3` heat
/// - `next_offset`: empty for first page
Future<ReplyListDto> replyList({
  required PlatformInt64 oid,
  required int type,
  required int mode,
  required String nextOffset,
}) => RustLib.instance.api.crateApiSocialReplyList(
  oid: oid,
  type: type,
  mode: mode,
  nextOffset: nextOffset,
);

/// One danmaku segment for `cid` (`segment_index` is **1-based**; `0` → `1`).
///
/// Soft-caps to 4000 items per segment for UI performance.
Future<DanmakuSegmentDto> danmakuSegments({
  required PlatformInt64 aid,
  required PlatformInt64 cid,
  required int segmentIndex,
}) => RustLib.instance.api.crateApiSocialDanmakuSegments(
  aid: aid,
  cid: cid,
  segmentIndex: segmentIndex,
);

/// Post a main-floor comment (or nested when `root`/`parent` > 0).
///
/// Requires login. `oid` is video **aid** for `type_=1`.
Future<ReplyDto> replyAdd({
  required PlatformInt64 oid,
  required int type,
  required String message,
  required PlatformInt64 root,
  required PlatformInt64 parent,
}) => RustLib.instance.api.crateApiSocialReplyAdd(
  oid: oid,
  type: type,
  message: message,
  root: root,
  parent: parent,
);

/// Post a video danmaku at `progress_ms` (Cookie + WBI).
///
/// - `oid`: **cid**
/// - `mode`: 0/1 scroll · 4 bottom · 5 top
/// - `color`: 0 → white
Future<DanmakuItemDto> danmakuPost({
  required PlatformInt64 oid,
  required PlatformInt64 aid,
  required String bvid,
  required String msg,
  required PlatformInt64 progressMs,
  required int mode,
  required int color,
}) => RustLib.instance.api.crateApiSocialDanmakuPost(
  oid: oid,
  aid: aid,
  bvid: bvid,
  msg: msg,
  progressMs: progressMs,
  mode: mode,
  color: color,
);

/// Single danmaku item on the player timeline.
class DanmakuItemDto {
  final PlatformInt64 id;
  final PlatformInt64 progressMs;
  final int mode;
  final int fontsize;
  final int color;
  final String text;
  final String midHash;

  const DanmakuItemDto({
    required this.id,
    required this.progressMs,
    required this.mode,
    required this.fontsize,
    required this.color,
    required this.text,
    required this.midHash,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      progressMs.hashCode ^
      mode.hashCode ^
      fontsize.hashCode ^
      color.hashCode ^
      text.hashCode ^
      midHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DanmakuItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          progressMs == other.progressMs &&
          mode == other.mode &&
          fontsize == other.fontsize &&
          color == other.color &&
          text == other.text &&
          midHash == other.midHash;
}

/// Segment payload (one ~6 min window).
class DanmakuSegmentDto {
  final int segmentIndex;
  final List<DanmakuItemDto> items;

  const DanmakuSegmentDto({required this.segmentIndex, required this.items});

  @override
  int get hashCode => segmentIndex.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DanmakuSegmentDto &&
          runtimeType == other.runtimeType &&
          segmentIndex == other.segmentIndex &&
          items == other.items;
}

/// One comment for Flutter lists.
class ReplyDto {
  final PlatformInt64 rpid;
  final PlatformInt64 mid;
  final String uname;
  final String avatar;
  final String content;
  final PlatformInt64 ctimeMs;
  final PlatformInt64 like;
  final int childrenCount;

  const ReplyDto({
    required this.rpid,
    required this.mid,
    required this.uname,
    required this.avatar,
    required this.content,
    required this.ctimeMs,
    required this.like,
    required this.childrenCount,
  });

  @override
  int get hashCode =>
      rpid.hashCode ^
      mid.hashCode ^
      uname.hashCode ^
      avatar.hashCode ^
      content.hashCode ^
      ctimeMs.hashCode ^
      like.hashCode ^
      childrenCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplyDto &&
          runtimeType == other.runtimeType &&
          rpid == other.rpid &&
          mid == other.mid &&
          uname == other.uname &&
          avatar == other.avatar &&
          content == other.content &&
          ctimeMs == other.ctimeMs &&
          like == other.like &&
          childrenCount == other.childrenCount;
}

/// Paginated main-floor reply list.
class ReplyListDto {
  final List<ReplyDto> replies;

  /// Pass as `next_offset` on the next call; empty when finished.
  final String nextOffset;
  final bool isEnd;
  final PlatformInt64 allCount;

  const ReplyListDto({
    required this.replies,
    required this.nextOffset,
    required this.isEnd,
    required this.allCount,
  });

  @override
  int get hashCode =>
      replies.hashCode ^
      nextOffset.hashCode ^
      isEnd.hashCode ^
      allCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplyListDto &&
          runtimeType == other.runtimeType &&
          replies == other.replies &&
          nextOffset == other.nextOffset &&
          isEnd == other.isEnd &&
          allCount == other.allCount;
}
