// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_main`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Watch history (main slot · Cookie). Cursor IFS: first call `max=0, view_at=0, business=""`.
///
/// `ps` defaults to 20 when 0.
Future<HistoryPageDto> historyList({
  required PlatformInt64 max,
  required PlatformInt64 viewAt,
  required String business,
  required int ps,
}) => RustLib.instance.api.crateApiUserHistoryList(
  max: max,
  viewAt: viewAt,
  business: business,
  ps: ps,
);

/// Watch-later list. `pn` starts at 1; `ps` default 20.
Future<ToViewPageDto> toviewList({required int pn, required int ps}) =>
    RustLib.instance.api.crateApiUserToviewList(pn: pn, ps: ps);

/// Favorite folders created by the signed-in user.
///
/// Pass `rid` (aid) > 0 to mark each folder's `in_folder` for that archive.
Future<FavFolderListDto> favFolders({required PlatformInt64 rid}) =>
    RustLib.instance.api.crateApiUserFavFolders(rid: rid);

/// Resources in a favorite folder. `pn` starts at 1; `ps` default 20.
Future<FavResourcePageDto> favResources({
  required PlatformInt64 mediaId,
  required int pn,
  required int ps,
}) => RustLib.instance.api.crateApiUserFavResources(
  mediaId: mediaId,
  pn: pn,
  ps: ps,
);

/// Favorite folder.
class FavFolderDto {
  final PlatformInt64 id;
  final String title;
  final int mediaCount;
  final String cover;
  final int attr;

  /// True when listed with a resource `rid` and that resource is in this folder.
  final bool inFolder;

  const FavFolderDto({
    required this.id,
    required this.title,
    required this.mediaCount,
    required this.cover,
    required this.attr,
    required this.inFolder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      mediaCount.hashCode ^
      cover.hashCode ^
      attr.hashCode ^
      inFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavFolderDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          mediaCount == other.mediaCount &&
          cover == other.cover &&
          attr == other.attr &&
          inFolder == other.inFolder;
}

/// Created folders list.
class FavFolderListDto {
  final List<FavFolderDto> folders;
  final int count;

  const FavFolderListDto({required this.folders, required this.count});

  @override
  int get hashCode => folders.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavFolderListDto &&
          runtimeType == other.runtimeType &&
          folders == other.folders &&
          count == other.count;
}

/// Media inside a favorite folder.
class FavResourceItemDto {
  final PlatformInt64 aid;
  final String bvid;
  final String title;
  final String cover;
  final String ownerName;
  final PlatformInt64 durationMs;
  final PlatformInt64 favTimeMs;

  const FavResourceItemDto({
    required this.aid,
    required this.bvid,
    required this.title,
    required this.cover,
    required this.ownerName,
    required this.durationMs,
    required this.favTimeMs,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      ownerName.hashCode ^
      durationMs.hashCode ^
      favTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavResourceItemDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          title == other.title &&
          cover == other.cover &&
          ownerName == other.ownerName &&
          durationMs == other.durationMs &&
          favTimeMs == other.favTimeMs;
}

/// Folder contents page.
class FavResourcePageDto {
  final List<FavResourceItemDto> items;
  final PlatformInt64 mediaId;
  final int pn;
  final bool hasMore;

  const FavResourcePageDto({
    required this.items,
    required this.mediaId,
    required this.pn,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ mediaId.hashCode ^ pn.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavResourcePageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          mediaId == other.mediaId &&
          pn == other.pn &&
          hasMore == other.hasMore;
}

/// Watch-history row.
class HistoryItemDto {
  final PlatformInt64 aid;
  final String bvid;
  final PlatformInt64 cid;
  final String title;
  final String cover;
  final String ownerName;
  final PlatformInt64 durationMs;
  final PlatformInt64 progressMs;
  final PlatformInt64 viewAtMs;
  final String business;
  final PlatformInt64 kid;
  final String showTitle;

  const HistoryItemDto({
    required this.aid,
    required this.bvid,
    required this.cid,
    required this.title,
    required this.cover,
    required this.ownerName,
    required this.durationMs,
    required this.progressMs,
    required this.viewAtMs,
    required this.business,
    required this.kid,
    required this.showTitle,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      cid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      ownerName.hashCode ^
      durationMs.hashCode ^
      progressMs.hashCode ^
      viewAtMs.hashCode ^
      business.hashCode ^
      kid.hashCode ^
      showTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryItemDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          cid == other.cid &&
          title == other.title &&
          cover == other.cover &&
          ownerName == other.ownerName &&
          durationMs == other.durationMs &&
          progressMs == other.progressMs &&
          viewAtMs == other.viewAtMs &&
          business == other.business &&
          kid == other.kid &&
          showTitle == other.showTitle;
}

/// History cursor page.
class HistoryPageDto {
  final List<HistoryItemDto> items;
  final PlatformInt64 nextMax;
  final PlatformInt64 nextViewAt;
  final String nextBusiness;
  final bool hasMore;

  const HistoryPageDto({
    required this.items,
    required this.nextMax,
    required this.nextViewAt,
    required this.nextBusiness,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      nextMax.hashCode ^
      nextViewAt.hashCode ^
      nextBusiness.hashCode ^
      hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextMax == other.nextMax &&
          nextViewAt == other.nextViewAt &&
          nextBusiness == other.nextBusiness &&
          hasMore == other.hasMore;
}

/// Watch-later row.
class ToViewItemDto {
  final PlatformInt64 aid;
  final String bvid;
  final PlatformInt64 cid;
  final String title;
  final String cover;
  final String ownerName;
  final PlatformInt64 durationMs;
  final PlatformInt64 progressMs;
  final PlatformInt64 addAtMs;

  const ToViewItemDto({
    required this.aid,
    required this.bvid,
    required this.cid,
    required this.title,
    required this.cover,
    required this.ownerName,
    required this.durationMs,
    required this.progressMs,
    required this.addAtMs,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      cid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      ownerName.hashCode ^
      durationMs.hashCode ^
      progressMs.hashCode ^
      addAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToViewItemDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          cid == other.cid &&
          title == other.title &&
          cover == other.cover &&
          ownerName == other.ownerName &&
          durationMs == other.durationMs &&
          progressMs == other.progressMs &&
          addAtMs == other.addAtMs;
}

/// Watch-later page.
class ToViewPageDto {
  final List<ToViewItemDto> items;
  final int count;
  final int pn;
  final bool hasMore;

  const ToViewPageDto({
    required this.items,
    required this.count,
    required this.pn,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ count.hashCode ^ pn.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToViewPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          count == other.count &&
          pn == other.pn &&
          hasMore == other.hasMore;
}
