// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Fetch video detail by bvid or aid string (e.g. `BV1…` / `av170001` / `170001`).
Future<VideoDetailDto> videoDetail({required String id}) =>
    RustLib.instance.api.crateApiVideoVideoDetail(id: id);

/// Video detail DTO for Flutter.
class VideoDetailDto {
  final PlatformInt64 aid;
  final String bvid;
  final String title;
  final String cover;
  final String desc;
  final PlatformInt64 ownerMid;
  final String ownerName;
  final String ownerFace;
  final List<VideoPageDto> pages;
  final VideoStatDto stat;
  final PlatformInt64 durationMs;

  const VideoDetailDto({
    required this.aid,
    required this.bvid,
    required this.title,
    required this.cover,
    required this.desc,
    required this.ownerMid,
    required this.ownerName,
    required this.ownerFace,
    required this.pages,
    required this.stat,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      bvid.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      desc.hashCode ^
      ownerMid.hashCode ^
      ownerName.hashCode ^
      ownerFace.hashCode ^
      pages.hashCode ^
      stat.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoDetailDto &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          bvid == other.bvid &&
          title == other.title &&
          cover == other.cover &&
          desc == other.desc &&
          ownerMid == other.ownerMid &&
          ownerName == other.ownerName &&
          ownerFace == other.ownerFace &&
          pages == other.pages &&
          stat == other.stat &&
          durationMs == other.durationMs;
}

/// One part (分 P) in a multi-part archive.
class VideoPageDto {
  final PlatformInt64 cid;
  final int page;
  final String part_;
  final PlatformInt64 durationMs;

  const VideoPageDto({
    required this.cid,
    required this.page,
    required this.part_,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      cid.hashCode ^ page.hashCode ^ part_.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoPageDto &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          page == other.page &&
          part_ == other.part_ &&
          durationMs == other.durationMs;
}

/// Archive statistics.
class VideoStatDto {
  final PlatformInt64 view;
  final PlatformInt64 danmaku;
  final PlatformInt64 reply;
  final PlatformInt64 favorite;
  final PlatformInt64 coin;
  final PlatformInt64 share;
  final PlatformInt64 like;

  const VideoStatDto({
    required this.view,
    required this.danmaku,
    required this.reply,
    required this.favorite,
    required this.coin,
    required this.share,
    required this.like,
  });

  @override
  int get hashCode =>
      view.hashCode ^
      danmaku.hashCode ^
      reply.hashCode ^
      favorite.hashCode ^
      coin.hashCode ^
      share.hashCode ^
      like.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoStatDto &&
          runtimeType == other.runtimeType &&
          view == other.view &&
          danmaku == other.danmaku &&
          reply == other.reply &&
          favorite == other.favorite &&
          coin == other.coin &&
          share == other.share &&
          like == other.like;
}
