//! Application core and FRB entrypoint.
//!
//! Flutter talks only to this crate.

pub mod api;
pub mod app;
pub mod auth_service;
pub mod error;
pub mod heartbeat;

/// Generated by `flutter_rust_bridge_codegen` (`scripts/codegen.sh`).
/// Do not edit by hand.
mod frb_generated;

pub use api::{
    api_version, bootstrap, device_buvid3, feed_popular, feed_recommend, get_settings,
    list_accounts, login_captcha, login_qr_poll, login_qr_start, login_sms, login_sms_send, logout,
    new_login_session_id, ping, play_url, playback_start, playback_stop, set_account_slot,
    update_settings, video_detail, AccountPublicDto, ApiVersion, BootstrapConfig, CaptchaDto,
    FeedItemDto, HeaderDto, MediaFormatDto, MediaSourceDto, PopularFeedDto, QrPollDto, QrStartDto,
    QrStatusKind, RecommendFeedDto, SettingsDto, SlotDto, SmsLoginDto, SmsSendDto,
    SmsSendDtoResult, StreamDto, SubtitleTrackDto, VideoDetailDto, VideoPageDto, VideoStatDto,
};
pub use app::CoreApp;
pub use error::{AppError, ErrorKind};

/// Crate semantic version exposed over FFI.
pub const CORE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// FFI API compatibility version (major bumps on breaking changes).
pub const API_MAJOR: u32 = 0;
pub const API_MINOR: u32 = 5;
pub const API_PATCH: u32 = 0;
